/* Standalone design reference. All facts are synthetic; no networking or persistence.
   Financial projections are fixtures. Only snapshot differences are calculated here. */
'use strict';
const $ = (s, root = document) => root.querySelector(s);
const $$ = (s, root = document) => [...root.querySelectorAll(s)];
const esc = value => String(value ?? '').replace(/[&<>"']/g, c => ({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const number = value => value == null ? '—' : new Intl.NumberFormat('en-US', { maximumFractionDigits: 6 }).format(value);
const signed = value => value == null ? '—' : `${value > 0 ? '+' : value < 0 ? '−' : ''}${value!==0&&Math.abs(value)<0.000001?'&lt;0.000001':number(Math.abs(value))}`;
const paths = {
 grid:'M3 3h7v7H3z M14 3h7v7h-7z M3 14h7v7H3z M14 14h7v7h-7z',
 portfolio:'M4 7h16v13H4z M8 7V4h8v3 M4 12h16 M10 12v3h4v-3',
 transactions:'M4 7h15m-4-4 4 4-4 4 M20 17H5m4-4-4 4 4 4',
 journal:'M5 3h14v18H5z M9 7h6 M9 11h6 M9 15h3',
 reconcile:'M8 3h8v3H8z M8 5H5v16h14V5h-3 M8 12l2 2 5-5 M8 18h7',
 transfer:'M7 15V3m-4 4 4-4 4 4 M17 9v12m-4-4 4 4 4-4',
 search:'M10.5 18a7.5 7.5 0 1 1 0-15 7.5 7.5 0 0 1 0 15 M16 16l5 5',
 chart:'M3 3v18h18 M7 15l4-5 4 3 5-7',
 globe:'M21 12a9 9 0 1 1-18 0 9 9 0 0 1 18 0 M3 12h18 M12 3c5 5 5 13 0 18-5-5-5-13 0-18',
 check:'M5 12l4 4L19 6',
 warning:'M12 3 2 21h20L12 3 M12 9v5 M12 17v.1',
 missing:'M21 12a9 9 0 1 1-18 0 9 9 0 0 1 18 0 M8 12h8',
 unknown:'M21 12a9 9 0 1 1-18 0 9 9 0 0 1 18 0 M9.5 9a2.5 2.5 0 1 1 4 2c-1.5 1-1.5 1-1.5 3 M12 17v.1',
 shield:'M12 3 4 6v6c0 4 4 7 8 9 4-2 8-5 8-9V6l-8-3 M8 12l3 3 5-6',
 lock:'M6 10h12v11H6z M8 10V7a4 4 0 0 1 8 0v3 M12 14v3',
 arrow:'M4 12h16m-6-6 6 6-6 6',
 chevron:'m7 10 5 5 5-5',
 plus:'M12 5v14 M5 12h14',
 close:'m6 6 12 12 M6 18 18 6',
 sun:'M16 12a4 4 0 1 1-8 0 4 4 0 0 1 8 0 M12 2v2 M12 20v2 M2 12h2 M20 12h2 M5 5l1.5 1.5 M17.5 17.5 1.5 1.5 M5 19l1.5-1.5 M17.5 6.5 19 5',
 menu:'M4 6h16 M4 12h16 M4 18h16',
 clock:'M21 12a9 9 0 1 1-18 0 9 9 0 0 1 18 0 M12 7v5l3 2',
 file:'M6 3h8l4 4v14H6z M14 3v5h4 M9 12h6 M9 16h4',
 upload:'M12 16V3m-5 5 5-5 5 5 M4 16v5h16v-5',
 download:'M12 3v13m-5-5 5 5 5-5 M4 17v4h16v-4',
 layers:'m12 3 10 6-10 6L2 9l10-6 M2 13l10 6 10-6 M2 17l10 6 10-6',
 info:'M21 12a9 9 0 1 1-18 0 9 9 0 0 1 18 0 M12 11v6 M12 7v.1',
 history:'M3 11a9 9 0 1 1 2 7 M3 4v7h7 M12 7v5l4 2',
 palette:'M12 3a9 9 0 1 0 0 18h2c2 0 3-2 2-3-2-2-1-3 1-3h1c6 0 3-12-6-12 M7 8h.1 M12 6h.1 M17 9h.1 M6 13h.1'
};
const icon = name => `<svg viewBox="0 0 24 24" aria-hidden="true"><path d="${paths[name] || paths.info}"/></svg>`;
const badge = (text, kind = 'outline', symbol = '') => `<span class="badge ${kind}">${symbol ? icon(symbol) : ''}${esc(text)}</span>`;
const statusBadge = status => {
 const definitions = { MATCH:['Match','match','check'], REVIEW:['Review','review','warning'], MISSING_FROM_LEDGER:['Missing from ledger','missing','journal'], MISSING_FROM_EXPECTED:['Missing from expected','missing-expected','file'], UNKNOWN_INSTRUMENT:['Unknown instrument','unknown','unknown'] };
 const [text, kind, symbol] = definitions[status];
 return `<span title="${status}">${badge(text,kind,symbol)}</span>`;
};
const ledger = [
 {symbol:'BBCA',name:'Bank Central Asia',shares:1200,avg:9150,price:9450,value:11340000,pnl:360000,pct:3.28,mandate:'INVEST',quality:'EOD · 30 Sep',kind:'match'},
 {symbol:'BBRI',name:'Bank Rakyat Indonesia',shares:2500,avg:4020,price:3890,value:9725000,pnl:-325000,pct:-3.23,mandate:'LONG_SWING',quality:'Degraded · 30 Sep',kind:'review'},
 {symbol:'TLKM',name:'Telkom Indonesia',shares:2000,avg:2890,price:3020,value:6040000,pnl:260000,pct:4.50,mandate:'INVEST',quality:'EOD · 30 Sep',kind:'match'},
 {symbol:'ASII',name:'Astra International',shares:1000,avg:4725,price:null,value:null,pnl:null,pct:null,mandate:'INVEST',quality:'No price',kind:'unknown'},
 {symbol:'ANTM',name:'Aneka Tambang',shares:3000,avg:1810,price:1940,value:5820000,pnl:390000,pct:7.18,mandate:'FAST_SWING',quality:'Stale · 29 Sep',kind:'info'},
 {symbol:'ICBP',name:'Indofood CBP',shares:400,avg:10750,price:10825,value:4330000,pnl:30000,pct:.70,mandate:'INVEST',quality:'EOD · 30 Sep',kind:'match'}
];
const ledgerCash = 8750000;
const names = Object.fromEntries([...ledger.map(h => [h.symbol,h.name]),['GOTO','GoTo Gojek Tokopedia']]);
const defaultExpected = () => [
 {symbol:'BBCA',shares:1200,avg:9150},{symbol:'BBRI',shares:2600,avg:4015},
 {symbol:'TLKM',shares:2000,avg:2890},{symbol:'ASII',shares:1000,avg:4725},
 {symbol:'ANTM',shares:3000,avg:1810},{symbol:'GOTO',shares:10000,avg:65},{symbol:'XXXX',shares:500,avg:100}
];
const state = { page:'reconcile', expected:defaultExpected(), cash:8700000, through:'2026-09-30', cutoff:'2026-10-01T08:00', result:null, resultFilter:'all', editorOpen:false, scenario:'review', error:'', importFormat:'CSV', importStep:1, fileName:'', importBad:false, restoreMode:'CREATE_NEW', thesisSymbol:'BBCA', transactionFilter:'all', transactionSearch:'' };
const transactions = [
 {id:'evt-009',trade:'30 Sep 2026',recorded:'01 Oct, 07:42',symbol:'BBRI',type:'BUY',quantity:500,price:3890,fees:2918,source:'Generic CSV',ref:'SYN-0930-009',status:'Active'},
 {id:'evt-008',trade:'29 Sep 2026',recorded:'30 Sep, 18:20',symbol:'ANTM',type:'SELL',quantity:500,price:1940,fees:2425,source:'Manual',ref:'SYN-0929-008',status:'Active'},
 {id:'evt-006',trade:'24 Sep 2026',recorded:'25 Sep, 09:12',symbol:'TLKM',type:'BUY',quantity:500,price:3400,fees:2550,source:'Generic CSV',ref:'SYN-0924-006',status:'Superseded'},
 {id:'evt-007',trade:'24 Sep 2026',recorded:'27 Sep, 10:30',symbol:'TLKM',type:'BUY',quantity:500,price:3450,fees:2550,source:'Manual',ref:'SYN-CORR-007',status:'Active',supersedes:'evt-006'},
 {id:'evt-005',trade:'22 Sep 2026',recorded:'23 Sep, 08:05',symbol:'BBCA',type:'BUY',quantity:400,price:9150,fees:5490,source:'Generic CSV',ref:'SYN-0922-005',status:'Active'},
 {id:'evt-004',trade:'21 Sep 2026',recorded:'21 Sep, 16:45',symbol:null,type:'CASH_DEPOSIT',quantity:null,price:null,cash:5000000,fees:0,source:'Manual',ref:'SYN-CASH-004',status:'Active'},
 {id:'evt-003',trade:'18 Sep 2026',recorded:'19 Sep, 08:15',symbol:'ASII',type:'BUY',quantity:1000,price:4725,fees:7088,source:'Generic CSV',ref:'SYN-0918-003',status:'Active'},
 {id:'evt-002',trade:'16 Sep 2026',recorded:'16 Sep, 15:30',symbol:null,type:'CASH_WITHDRAWAL',quantity:null,price:null,cash:1000000,fees:0,source:'Manual',ref:'SYN-CASH-002',status:'Active'}
];
const thesisFixtures = [
 {version:2,mandate:'INVEST',active:true,date:'25 Sep 2026, 10:15 WIB',text:'The position is now held with a longer investment horizon. Monitor the durability of deposit funding, asset quality, and earnings delivery against the original thesis. This mandate change is intentional; it is not a response to short-term price movement.',invalidation:'Reassess if asset quality deteriorates across two reported periods, or if the original funding-cost assumptions no longer hold.'},
 {version:1,mandate:'FAST_SWING',active:true,date:'10 Sep 2026, 09:20 WIB',text:'A time-bounded swing position with a defined review window. Review the original assumptions at the end of the planned holding period.',invalidation:'Close the thesis review if the planned holding period expires without the expected development.'}
];
state.theses = { BBCA: structuredClone(thesisFixtures) };
let toastTimer;
function toast(message) { const el=$('#toast');el.textContent=message;el.hidden=false;clearTimeout(toastTimer);toastTimer=setTimeout(()=>el.hidden=true,5000); }
function symbolCell(symbol, compact=false) { return `<div class="symbol-cell">${compact?'':`<span class="symbol-mark" aria-hidden="true">${esc(symbol.slice(0,1))}</span>`}<span><span class="symbol-name">${esc(symbol)}</span><span class="symbol-description">${esc(names[symbol] || 'Unresolved symbol')}</span></span></div>`; }
function pageHeader(eyebrow,title,description,actions='') { return `<div class="page-header"><div><p class="eyebrow">${eyebrow}</p><h1>${title}</h1><p class="page-subtitle">${description}</p></div><div class="header-actions">${actions}</div></div>`; }
function notice(text, kind='', symbol='info', action='') { return `<div class="notice ${kind}">${icon(symbol)}<div>${text}</div>${action}</div>`; }
function metric(label,value,note='',cls='') { return `<div class="metric"><span class="metric-label">${label}</span><strong class="metric-value number ${cls}">${value}</strong>${note?`<span class="metric-note">${note}</span>`:''}</div>`; }
function nav() {
 const entries=[['overview','Overview','grid'],['portfolio','Portfolio','portfolio'],['transactions','Transactions','transactions'],['thesis','Thesis','journal'],['reconcile','Reconcile','reconcile'],['import','Import / Export','transfer']];
 $('#navigation').innerHTML=entries.map(([page,label,symbol])=>`<button class="nav-link ${state.page===page?'active':''}" data-page="${page}" ${state.page===page?'aria-current="page"':''} title="${label}">${icon(symbol)}<span class="nav-text">${label}</span></button>`).join('')+`<div class="nav-label">RESEARCH · COMING LATER</div>`+[['Screener','search'],['Stocks','chart'],['Market','globe']].map(([label,symbol])=>`<button class="nav-link" disabled title="${label} — reserved for a future milestone">${icon(symbol)}<span class="nav-text">${label}</span><small>Later</small></button>`).join('');
 const labels={overview:'Overview',portfolio:'Portfolio',transactions:'Transactions',thesis:'Thesis',reconcile:'Reconcile',import:'Import / Export',system:'Design system'};
 $('#breadcrumb-current').textContent=labels[state.page];document.title=`${labels[state.page]} · IDX Intelligence`;
}
function expectedRows() { return state.expected.map((h,i)=>`<tr><td><input aria-label="Holding ${i+1} symbol" data-row="${i}" data-field="symbol" value="${esc(h.symbol)}" maxlength="20" required placeholder="e.g. BBCA"></td><td><input class="num" aria-label="Holding ${i+1} shares" data-row="${i}" data-field="shares" type="number" min="1" max="1000000000" step="1" value="${h.shares}" required></td><td><input class="num" aria-label="Holding ${i+1} average cost in IDR" data-row="${i}" data-field="avg" type="number" min="0" max="1000000000000" step="any" value="${h.avg}" required></td><td><button type="button" class="icon-button" data-action="remove-holding" data-row="${i}" aria-label="Remove holding ${i+1}">${icon('close')}</button></td></tr>`).join(''); }
function compareSnapshot() {
 const rows=[];const expected=new Map();
 for(const h of state.expected) {
  const symbol=h.symbol.trim().toUpperCase();
  if(!symbol || !Number.isSafeInteger(h.shares) || h.shares<=0 || !Number.isFinite(h.avg) || h.avg<0) throw new Error('Each holding needs a symbol, a positive whole share quantity, and a nonnegative average cost.');
  if(expected.has(symbol)) throw new Error(`${symbol} is entered twice. Keep one snapshot row per holding.`);
  expected.set(symbol,{...h,symbol});
 }
 for(const l of ledger) {
  const e=expected.get(l.symbol);
  rows.push({symbol:l.symbol,ledger:l,expected:e,shareDiff:e?l.shares-e.shares:null,costDiff:e?l.avg-e.avg:null,status:!e?'MISSING_FROM_EXPECTED':l.shares===e.shares&&l.avg===e.avg?'MATCH':'REVIEW'});
  expected.delete(l.symbol);
 }
 for(const e of expected.values()) rows.push({symbol:e.symbol,ledger:null,expected:e,shareDiff:null,costDiff:null,status:names[e.symbol]?'MISSING_FROM_LEDGER':'UNKNOWN_INSTRUMENT'});
 return {rows,cash:state.cash,cashDiff:ledgerCash-state.cash};
}
state.result=compareSnapshot();
function reconciliation() {
 return pageHeader('PORTFOLIO OPERATIONS','Portfolio reconciliation','A clear comparison between your ledger and your broker snapshot.',`<span class="readonly-label">${icon('shield')}Read-only comparison</span>`)+
 `<form id="snapshot-form" class="panel"><div class="panel-head"><div class="panel-title"><span class="step-number">01</span><h2>Broker snapshot</h2></div><div class="actions"><span class="muted">IDR · quantities in shares</span><button type="button" class="text-button" data-action="toggle-snapshot" aria-expanded="${state.editorOpen}" aria-controls="snapshot-editor">${state.editorOpen?'Hide inputs':'Edit snapshot'} ${icon('chevron')}</button></div></div>
 <div id="snapshot-editor" ${state.editorOpen?'':'hidden'}><div class="fields"><label class="field"><span>As-of / through date</span><input type="date" id="through" value="${state.through}" required><small>Include trades through this date</small></label><label class="field"><span>Knowledge cutoff <span class="muted">· WIB / UTC+7</span></span><input type="datetime-local" id="cutoff" value="${state.cutoff}" required><small>Only facts recorded by this time</small></label><label class="field"><span>Expected cash</span><span class="input-prefix"><span>Rp</span><input id="expected-cash" aria-label="Expected cash in IDR" type="text" inputmode="decimal" pattern="[0-9]+(,[0-9]{3})*(\\.[0-9]{1,2})?" value="${number(state.cash)}" required></span><small>Available cash on your broker snapshot</small></label></div>
 <details class="snapshot-holdings" id="expected-details"><summary>${icon('layers')}<strong id="expected-count">${state.expected.length} holdings entered</strong><span class="summary-symbols">BBCA, BBRI, TLKM + ${Math.max(0,state.expected.length-3)} more</span><span class="summary-action">Edit snapshot ${icon('chevron')}</span></summary><div class="table-scroll"><table class="expected-table"><thead><tr><th>Symbol</th><th class="num">Shares</th><th class="num">Average cost · IDR</th><th><span class="sr-only">Remove</span></th></tr></thead><tbody id="expected-rows">${expectedRows()}</tbody></table></div><button type="button" class="text-button add-row" data-action="add-holding">${icon('plus')}Add holding</button></details>
 </div><div id="snapshot-error" ${state.error?'':'hidden'} class="notice error" role="alert">${esc(state.error)}</div>
 <div class="panel-footer"><p>${icon('lock')}<span id="snapshot-caption">${state.expected.length} holdings · Expected cash <strong>Rp${Number.isFinite(state.cash)?number(state.cash):'—'}</strong></span><span class="muted">· Read-only</span></p><div class="actions"><button class="button ghost" type="button" data-action="reset-snapshot">Reset example</button><button class="button primary" type="submit">Compare Portfolio ${icon('arrow')}</button></div></div></form>
 <div class="section-heading"><div class="panel-title"><span class="step-number">02</span><h2>Comparison results</h2></div><span class="muted">Ledger − broker snapshot</span></div><div id="reconcile-result" aria-live="polite">${reconcileResult()}</div>`;
}
function reconcileResult() {
 if(state.scenario==='loading') return `<div class="panel" aria-busy="true"><p class="loading-text"><span class="spinner"></span>Comparing the recorded portfolio…</p>${Array.from({length:5},()=>`<div class="skeleton-row">${'<div class="skeleton"></div>'.repeat(5)}</div>`).join('')}</div>`;
 if(state.scenario==='error') return `<div class="panel"><div class="empty-state">${icon('warning')}<h3>Comparison could not be completed</h3><p>Your snapshot inputs are still here. Your ledger has not changed.</p><button class="button" data-action="retry-compare">Try comparison again ${icon('arrow')}</button></div></div>`;
 if(!state.result || state.scenario==='empty') return `<div class="panel"><div class="empty-state">${icon('reconcile')}<h3>${state.scenario==='empty'?'Ready when your snapshot is':'Snapshot changed'}</h3><p>${state.scenario==='empty'?'Enter the broker cash balance and holdings, then compare against your ledger.':'Compare again to see results for the updated snapshot. Previous results have been cleared.'}</p></div></div>`;
 const result=state.result, match=result.rows.filter(r=>r.status==='MATCH').length, review=result.rows.length-match, missing=result.rows.filter(r=>r.status.startsWith('MISSING_')).length, unknown=result.rows.filter(r=>r.status==='UNKNOWN_INSTRUMENT').length;
 const needsReview=review>0||result.cashDiff!==0;
 const shown=result.rows.filter(r=>state.resultFilter==='all'||r.status!=='MATCH');
 return `<div class="notice ${needsReview?'warning':''}" style="margin-bottom:15px">${icon(needsReview?'warning':'check')}<div><strong>${needsReview?'A few differences need your review':'Your snapshot matches the ledger'}</strong><span class="secondary"> · ${needsReview?`${review} holding${review===1?'':'s'}${result.cashDiff!==0?' and the cash balance':''} differ from your snapshot.`:'Cash and all expected holdings match for this point in time.'}</span></div>${badge(needsReview?'REVIEW':'MATCH',needsReview?'review':'match')}</div>
 <div class="summary-strip">${metric('Ledger cash',`<small>Rp</small>${number(ledgerCash)}`,'Reconstructed balance')}${metric('Expected cash',`<small>Rp</small>${number(result.cash)}`,'Broker snapshot')}${metric('Cash difference',`<small>Rp</small>${signed(result.cashDiff)}`,'Ledger − expected',result.cashDiff?'warn':'')}${metric('Matched holdings',`${match}<small>/ ${result.rows.length}</small>`,'No differences','count')}${metric('Require review',String(review),`${unknown} unknown instrument${unknown===1?'':'s'}`,'count '+(review?'warn':''))}${metric('Missing holdings',String(missing),'Across either source','count')}</div>
 <div class="panel results-panel"><div class="table-toolbar"><div class="tabs" role="tablist" aria-label="Reconciliation results"><button class="tab" role="tab" aria-selected="${state.resultFilter==='all'}" data-result-filter="all">All holdings <span class="tab-count">${result.rows.length}</span></button><button class="tab" role="tab" aria-selected="${state.resultFilter==='review'}" data-result-filter="review">Needs review <span class="tab-count">${review}</span></button></div><span class="table-note">${icon('info')}Differences = ledger − expected</span></div>
 <div class="table-scroll" tabindex="0" aria-label="Holding comparisons; scroll horizontally on smaller screens"><table class="reconcile-table"><caption class="sr-only">Share quantities and average costs compared with the broker snapshot. Missing values are not zero.</caption><thead><tr><th rowspan="2">Holding</th><th class="num" colspan="3">SHARES</th><th class="num group-separator" colspan="3">AVERAGE COST · IDR</th><th rowspan="2">Status</th></tr><tr><th class="num">Ledger</th><th class="num">Expected</th><th class="num">Difference</th><th class="num group-separator">Ledger</th><th class="num">Expected</th><th class="num">Difference</th></tr></thead><tbody>${shown.length?shown.map(r=>`<tr class="${r.status==='REVIEW'?'review-row':''}"><td>${symbolCell(r.symbol)}</td><td class="num">${number(r.ledger?.shares)}</td><td class="num">${number(r.expected?.shares)}</td><td class="num difference ${r.shareDiff?'mismatch':''}">${signed(r.shareDiff)}</td><td class="num group-separator">${number(r.ledger?.avg)}</td><td class="num">${number(r.expected?.avg)}</td><td class="num difference ${r.costDiff?'mismatch':''}">${signed(r.costDiff)}</td><td>${statusBadge(r.status)}</td></tr>`).join(''):'<tr><td colspan="8"><div class="empty-state">No holdings require review.</div></td></tr>'}</tbody></table></div><div class="table-bottom"><span>${shown.length} of ${result.rows.length} holdings <span class="footer-separator">·</span> — = not available in that source</span><span>30 Sep 2026 · known by 01 Oct, 08:00 WIB</span></div></div>
 ${notice('Differences are a prompt to check your source records. Any corrections remain explicit, new transactions.','subtle','shield',`<button class="text-button" data-page="transactions">View transactions ${icon('arrow')}</button>`)}`;
}
function portfolio() {
 return pageHeader('YOUR CAPITAL, IN CONTEXT',state.page==='overview'?'Portfolio overview':'Portfolio','Your positions, costs, and the quality of the data behind them.',`<button class="button" data-page="import">${icon('download')}Export portfolio</button><button class="button primary" data-page="reconcile">${icon('reconcile')}Reconcile</button>`)+
 `<div class="summary-strip portfolio-metrics">${metric('Portfolio value','Unavailable','Incomplete valuation')}${metric('Cash',`<small>Rp</small>8,750,000`,'Ledger balance')}${metric('Invested cost',`<small>Rp</small>41,265,000`,'Across 6 open holdings')}${metric('Unrealized P/L','Unavailable','Priced subtotal: +Rp715,000')}${metric('Realized P/L',`<small>Rp</small>+1,240,000`,'Synthetic ledger fixture','positive')}${metric('Data coverage','5<small>/ 6 priced</small>',`<span class="coverage-meter" aria-hidden="true">${'<i></i>'.repeat(6)}</span>`)}</div>
 ${notice('<strong>A complete valuation is not available.</strong> ASII has no market price. Priced holdings subtotal: <strong>Rp37,255,000</strong>. This excludes unpriced holdings.','info','info')}
 <div class="panel results-panel"><div class="table-toolbar"><div class="tabs"><span class="tab active">Holdings <span class="tab-count">6</span></span></div><span class="table-note">IDR · quantities in shares · prices retain their source dates</span></div><div class="table-scroll" tabindex="0" aria-label="Portfolio holdings"><table class="holdings-table"><thead><tr><th>Holding</th><th>Mandate</th><th class="num">Shares</th><th class="num">Avg. cost</th><th class="num">Current price</th><th class="num">Market value</th><th class="num">Unrealized P/L</th><th class="num">Unrealized %</th><th>Price / data state</th></tr></thead><tbody>${ledger.map(h=>`<tr><td><button class="text-button" data-action="holding" data-symbol="${h.symbol}" style="color:inherit;text-align:left">${symbolCell(h.symbol)}</button></td><td>${badge(h.mandate.replace('_',' '),'outline')}</td><td class="num">${number(h.shares)}</td><td class="num">${number(h.avg)}</td><td class="num">${number(h.price)}${h.price==null?'<span class="amount-secondary">Unavailable</span>':''}</td><td class="num">${number(h.value)}</td><td class="num ${h.pnl>0?'positive':h.pnl<0?'negative':'muted'}">${signed(h.pnl)}</td><td class="num ${h.pnl>0?'positive':h.pnl<0?'negative':'muted'}">${h.pct==null?'—':signed(h.pct)+'%'}</td><td>${badge(h.quality,h.kind==='review'?'degraded':h.kind,h.kind==='unknown'?'unknown':h.kind==='review'?'layers':h.kind==='info'?'clock':'check')}</td></tr>`).join('')}</tbody></table></div><div class="table-bottom"><span>6 open holdings · weighted-average cost from the ledger</span><span>Missing prices are never treated as zero</span></div></div>
 <div class="section-heading"><h2>Valuation notes</h2></div>${notice('Costs remain visible for every position. Market values depend on available prices at the selected date; unavailable values are never treated as zero.','','shield')}`;
}
function transactionRows() {
 const shown=transactions.filter(t=>(state.transactionFilter!=='corrections'||t.supersedes||t.status==='Superseded')&&`${t.symbol||'Cash'} ${t.ref} ${t.type}`.toLowerCase().includes(state.transactionSearch.toLowerCase()));
 return shown.length?shown.map(t=>`<tr class="${t.status==='Superseded'?'superseded':''} ${t.supersedes?'correction-child':''}"><td><span>${t.trade}</span>${t.supersedes?`<span class="correction-link">↳ correction of ${esc(t.supersedes)}</span>`:''}</td><td>${esc(t.recorded)}<span class="amount-secondary">2026 · WIB</span></td><td>${t.symbol?`<strong class="symbol-name">${t.symbol}</strong>`:'<span class="muted">Cash</span>'}</td><td>${badge(t.type.replace('CASH_','').replace('_',' '),t.type==='BUY'?'info':t.type==='SELL'?'missing':'outline')}</td><td class="num">${number(t.quantity)}${t.quantity!=null?'<span class="amount-secondary">shares</span>':''}</td><td class="num">${number(t.price ?? t.cash)}${t.cash?'<span class="amount-secondary">cash amount</span>':''}</td><td class="num">${number(t.fees)}</td><td>${t.source}<span class="amount-secondary mono">${esc(t.ref)}</span></td><td>${badge(t.status,t.status==='Active'?'match':'outline',t.status==='Active'?'check':'history')}</td><td><button class="text-button table-action" data-action="correct" data-event="${esc(t.id)}" aria-label="Correct transaction ${esc(t.id)}" ${t.status==='Superseded'?'disabled title="Correct the active replacement instead"':'title="Correct transaction"'}>${icon('history')}Correct</button></td></tr>`).join(''):'<tr><td colspan="10"><div class="empty-state">No matching transactions. Try another symbol or reference.</div></td></tr>';
}
function transactionPage() {
 return pageHeader('AN AUDITABLE HISTORY','Transactions','Every entry remains part of the record. Corrections append a new transaction.',`<span class="readonly-label">${icon('history')}Append-only ledger</span>`)+
 notice('<strong>Original entries stay intact.</strong> A correction supersedes an earlier fact from its recorded timestamp onward. Earlier knowledge cutoffs still show the original.','','history')+
 `<div class="panel results-panel"><div class="table-toolbar"><div class="tabs" role="tablist" aria-label="Transaction view"><button class="tab" role="tab" aria-selected="${state.transactionFilter==='all'}" data-transaction-filter="all">All transactions <span class="tab-count">${transactions.length}</span></button><button class="tab" role="tab" aria-selected="${state.transactionFilter==='corrections'}" data-transaction-filter="corrections">Correction chains</button></div><label class="search">${icon('search')}<span class="sr-only">Search symbol or reference</span><input id="transaction-search" placeholder="Symbol or reference…" value="${esc(state.transactionSearch)}"></label></div><div class="table-scroll" tabindex="0" aria-label="Transaction history"><table class="transaction-table"><thead><tr><th>Trade date</th><th>Recorded timestamp</th><th>Symbol</th><th>Type</th><th class="num">Quantity</th><th class="num">Price / cash · IDR</th><th class="num">Fees</th><th>Source / external ref.</th><th>State</th><th>Action</th></tr></thead><tbody id="transaction-rows">${transactionRows()}</tbody></table></div><div class="table-bottom"><span>Representative synthetic history · not the complete portfolio ledger</span><span>Dates are separate from recording time</span></div></div>
 ${notice('Follow the indented correction to see which entry replaced the original. Choose Correct to create a new event that supersedes the selected entry.','subtle','info')}`;
}
function correctionDialog(id) {
 const t=transactions.find(t=>t.id===id);if(!t||t.status!=='Active')return;
 const trade=!!t.symbol;
 openDialog(`<form id="correction-form" data-event="${esc(id)}"><div class="dialog-head"><div><p class="eyebrow">APPEND A CORRECTION</p><h2 id="dialog-title">Correct transaction</h2><p>${esc(t.symbol||'Cash')} · ${t.type.replaceAll('_',' ')} · ${t.trade}</p></div><button type="button" class="icon-button" data-action="close-dialog" aria-label="Close correction">${icon('close')}</button></div><div class="dialog-body">${notice('The original stays in history. Saving creates a new event that supersedes it.','','history')}<dl class="immutable"><div><dt>Original event ID · immutable</dt><dd class="mono">${t.id}</dd></div><div><dt>Original recorded timestamp · immutable</dt><dd>${t.recorded} 2026, WIB</dd></div></dl><div class="fields"><label class="field"><span>Trade date</span><input name="date" type="date" value="2026-09-${t.trade.slice(0,2)}" required max="2026-09-30"></label><label class="field"><span>Type</span><select name="type" class="control">${(trade?['BUY','SELL']:['CASH_DEPOSIT','CASH_WITHDRAWAL']).map(type=>`<option ${type===t.type?'selected':''}>${type}</option>`).join('')}</select></label>${trade?`<label class="field"><span>Quantity · SHARES</span><input name="quantity" type="number" value="${t.quantity}" min="1" step="1" required></label><label class="field"><span>Price · IDR</span><input name="price" type="number" value="${t.price}" min="0.01" step="any" required></label>`:`<label class="field"><span>Cash amount · IDR</span><input name="cash" type="number" value="${t.cash}" min="0.01" step="any" required></label>`}<label class="field"><span>Fees · IDR</span><input name="fees" type="number" value="${t.fees}" min="0" step="any" required></label><label class="field"><span>New external reference</span><input name="reference" value="SYN-CORR-${transactions.length+1}" maxlength="200" required></label></div><label class="field"><span>Correction note</span><textarea name="note" placeholder="Describe what changed and the source you checked…" maxlength="4000"></textarea></label><p class="muted" style="font-size:10px;margin-top:14px">Prototype only. This adds an example row in memory; it does not update a real ledger or recalculate balances.</p></div><div class="dialog-footer"><button type="button" class="button ghost" data-action="close-dialog">Cancel</button><button type="submit" class="button primary">Append correction ${icon('arrow')}</button></div></form>`);
}
function thesisPage() {
 const symbol=state.thesisSymbol,versions=state.theses[symbol]||[],current=versions[0];
 return pageHeader('WRITE THE REASON. KEEP THE RECORD.','Thesis & mandate','An explicit investment mandate, with a history you can return to.',`<span class="readonly-label">${icon('journal')}Versioned journal</span>`)+
 `<div class="thesis-layout"><div class="panel thesis-list"><div class="thesis-list-head">YOUR HOLDINGS · 6</div>${ledger.map(h=>`<button class="thesis-symbol ${h.symbol===symbol?'active':''}" data-thesis-symbol="${h.symbol}" aria-pressed="${h.symbol===symbol}">${symbolCell(h.symbol,true)}${badge(state.theses[h.symbol]?.length?'v'+state.theses[h.symbol][0].version:'—','outline')}</button>`).join('')}</div><div>${current?`<article class="panel thesis-current"><div class="thesis-current-top">${symbolCell(symbol)}${badge(current.active?'Active thesis':'Inactive thesis',current.active?'match':'outline',current.active?'check':'history')}</div><div class="thesis-meta">${badge(current.mandate.replace('_',' '),'info')}<span>Version ${current.version}</span><span>Recorded ${current.date}</span></div><p class="thesis-copy-label">Investment thesis</p><p class="thesis-copy">${esc(current.text)}</p><p class="thesis-copy-label">Invalidation condition / note</p><div class="invalidation">${esc(current.invalidation)}</div><div class="thesis-actions"><button class="button primary" data-action="new-thesis">${icon('plus')}Create New Version</button><button class="text-button muted" data-action="invalidate-thesis" ${current.active?'':'disabled'}>${icon('missing')}Invalidate Thesis</button></div></article><div class="section-heading"><h2>Version history</h2><span class="muted">Every version is retained</span></div><div class="timeline">${versions.map((v,i)=>`<div class="timeline-entry"><div class="timeline-top"><strong>v${v.version}</strong>${badge(v.active?v.mandate.replace('_',' '):'Inactive',v.active?'outline':'missing')}<span class="muted" style="font-size:10px">${i===0?'Current version':'Historical version'}</span><span class="timeline-date">${v.date}</span></div><p>${i===0?(v.active?'Explicitly recorded mandate and thesis.':'Thesis invalidated by a new version.'): 'Retained exactly as recorded. '+esc(v.text.slice(0,90))+'…'}</p><details><summary class="text-button">Read recorded version</summary><p>${esc(v.text)}</p><p>Invalidation: ${esc(v.invalidation)}</p></details></div>`).join('')}</div>`:`<div class="panel"><div class="empty-state">${icon('journal')}<h3>No thesis recorded for ${symbol}</h3><p>A position and a thesis are different records. Create a version to document the mandate and your own reasoning.</p><button class="button primary" data-action="new-thesis">${icon('plus')}Create New Version</button></div></div>`}${notice('Historical mandate changes remain visible. A position is never silently relabeled from a swing to an investment.','subtle','shield')}</div></div>`;
}
function thesisDialog(invalidate=false) {
 const current=state.theses[state.thesisSymbol]?.[0];
 openDialog(`<form id="thesis-form" data-invalidate="${invalidate}"><div class="dialog-head"><div><p class="eyebrow">${esc(state.thesisSymbol)} · NEW VERSION</p><h2 id="dialog-title">${invalidate?'Invalidate thesis':'Create new thesis version'}</h2><p>${invalidate?'The next version marks the thesis inactive.':'A fresh record, with all earlier versions preserved.'}</p></div><button class="icon-button" type="button" data-action="close-dialog" aria-label="Close thesis dialog">${icon('close')}</button></div><div class="dialog-body">${notice(invalidate?'Invalidation appends a version. It does not sell shares or delete your previous reasoning.':'Record a mandate change explicitly. This does not change your transactions.','','history')}<div class="stack"><label class="field"><span>Mandate</span><select class="control" name="mandate" ${invalidate?'disabled':''}>${['FAST_SWING','LONG_SWING','INVEST'].map(m=>`<option ${m===(current?.mandate||'INVEST')?'selected':''}>${m}</option>`).join('')}</select></label><label class="field"><span>Thesis</span><textarea name="text" required maxlength="8000" ${invalidate?'readonly':''}>${esc(current?.text||'')}</textarea></label><label class="field"><span>${invalidate?'Invalidation note':'Invalidation condition / note'}</span><textarea name="invalidation" required maxlength="4000" placeholder="What would invalidate this thesis?">${invalidate?'':esc(current?.invalidation||'')}</textarea></label></div><p class="muted" style="font-size:10px;margin-top:15px">Synthetic design preview. Changes last only until you reload.</p></div><div class="dialog-footer"><button class="button ghost" type="button" data-action="close-dialog">Cancel</button><button class="button ${invalidate?'danger':'primary'}" type="submit">${invalidate?'Append inactive version':'Create new version'}</button></div></form>`);
}
function importPage() {
 const isJson=state.importFormat==='JSON';
 return pageHeader('YOUR RECORDS, IN YOUR HANDS','Import & export','Bring in transactions, or restore your complete portfolio history.',`<span class="readonly-label">${icon('lock')}Your files stay local</span>`)+
 `<div class="import-layout"><div class="panel import-main"><div class="steps" aria-label="Import progress">${['Select file','Review preview','Confirm import'].map((s,i)=>`${i?'<span class="step-line"></span>':''}<span class="step ${state.importStep===i+1?'current':state.importStep>i+1?'done':''}" ${state.importStep===i+1?'aria-current="step"':''}><em>${state.importStep>i+1?'✓':i+1}</em>${s}</span>`).join('')}</div>
 ${state.importStep===1?`<h2 style="font-size:15px">What would you like to import?</h2><div class="format-options"><button class="format-option" data-import-format="CSV" aria-pressed="${!isJson}"><span class="format-title">CSV transactions ${!isJson?icon('check'):''}</span><p>Add transaction records to your open portfolio. Review quantities and duplicates first.</p></button><button class="format-option" data-import-format="JSON" aria-pressed="${isJson}"><span class="format-title">JSON portfolio backup ${isJson?icon('check'):''}</span><p>Restore the complete record: identities, corrections, thesis versions and dates.</p></button></div>
 ${isJson?`<label class="field" style="margin-bottom:20px"><span>Restore destination</span><select class="control" id="restore-mode"><option value="CREATE_NEW" ${state.restoreMode==='CREATE_NEW'?'selected':''}>Restore as a new portfolio</option><option value="RESTORE_EXISTING_EMPTY" ${state.restoreMode==='RESTORE_EXISTING_EMPTY'?'selected':''}>Restore into the original empty portfolio</option></select><small>The original portfolio identity is preserved. Existing history is never overwritten.</small></label>`:`<p class="muted" style="font-size:11px;margin-bottom:16px">Import into <strong class="secondary">Personal portfolio</strong> · generic CSV, not a broker-specific format</p>`}
 <div class="drop-zone" id="drop-zone"><span class="drop-icon">${icon('upload')}</span><p>${state.fileName?esc(state.fileName):'Drop your '+(isJson?'JSON backup':'CSV transaction file')+' here'}</p><small>${state.fileName?'Selected for the visual preview':'or choose a file from your computer'}</small><label class="button" for="import-file">${icon('file')}Choose file</label><input id="import-file" type="file" accept="${isJson?'.json':'.csv'}"><small>UTF-8 · up to 8 MiB</small></div><div id="file-error" class="notice error" role="alert" hidden></div><div class="import-actions"><button class="text-button" data-action="sample-file">Use synthetic ${state.importFormat} example</button><button class="button primary" data-action="preview-import" ${state.fileName?'':'disabled'}>Preview file ${icon('arrow')}</button></div><p class="muted" style="font-size:10px;margin-top:20px">Design preview: files are not read or uploaded. The next step shows fixed synthetic rows.</p>`:
 state.importStep===2?importPreview():`<div class="import-success"><span class="success-mark">${icon('check')}</span><h2>Import flow complete</h2><p>${isJson?'Portfolio restoration':'Transaction import'} confirmed in this design preview.</p><p style="margin-top:8px">Nothing was written. Your real portfolio is untouched.</p><button class="button" data-action="restart-import">Try another example ${icon('arrow')}</button></div>`}
 </div><aside class="panel import-side"><div><span class="download-icon">${icon('download')}</span><h3>A complete copy of your portfolio</h3><p>JSON is your canonical, lossless backup. It preserves the ledger, corrections and thesis history exactly as recorded.</p><button class="button" data-action="export-demo">${icon('download')}Export Portfolio · JSON</button></div><hr><div><h3>CSV is for onboarding</h3><p>Use generic CSV to bring in transactions. It does not preserve the complete history needed for a portfolio restore.</p><p style="margin-top:13px">Quantities must say <strong class="secondary">LOTS</strong> or <strong class="secondary">SHARES</strong>. Preview makes the normalization visible.</p></div></aside></div>`;
}
function importPreview() {
 const json=state.importFormat==='JSON';
 if(json) return `<div class="file-selected">${icon('file')}<div><strong>${esc(state.fileName)}</strong><small>Complete synthetic portfolio archive · JSON v1</small></div>${badge(state.importBad?'Conflict':'Ready for review',state.importBad?'review':'match')}</div>
 <div class="import-preview-stats"><div><strong>24</strong><span>Ledger events</span></div><div><strong>3</strong><span>Thesis versions</span></div><div><strong>6</strong><span>Instrument identities</span></div></div>
 ${notice(state.importBad?'<strong>This destination already contains history.</strong> The backup cannot replace existing records. Nothing will be imported.':'<strong>A complete history, with its original identity.</strong> Trade dates, recording times, corrections and every thesis version will be preserved.',state.importBad?'warning':'info',state.importBad?'warning':'shield')}
 <div class="stack" style="margin:22px 0"><div class="file-selected">${icon('portfolio')}<div><strong>${state.restoreMode==='CREATE_NEW'?'Restore original portfolio into a new destination':'Restore into the original empty portfolio'}</strong><small>The original portfolio UUID is preserved; no duplicate identity is created.</small></div></div><div class="file-selected">${icon('history')}<div><strong>1 correction chain · 3 thesis versions</strong><small>Original events, mandate changes and invalidation notes stay in history.</small></div></div></div>
 <p class="muted" style="font-size:11px">Market prices are not included in a portfolio backup. Holdings without a price remain visible.</p>
 <div class="import-actions"><button class="button ghost" data-action="back-import">Back to file</button><button class="button primary" data-action="confirm-import" ${state.importBad?'disabled':''}>Confirm Import ${icon('arrow')}</button></div><p class="muted" style="font-size:10px;margin-top:15px">Fixed synthetic archive preview. No selected file is read, validated or imported.</p>`;
 return `<div class="file-selected">${icon('file')}<div><strong>${esc(state.fileName)}</strong><small>Synthetic example preview · ${json?'lossless JSON restoration':'generic CSV transaction onboarding'}</small></div>${badge(state.importBad?'Needs review':'Ready for review',state.importBad?'review':'match')}</div>
 <div class="import-preview-stats"><div><strong>5</strong><span>Rows read</span></div><div><strong>${state.importBad?3:4}</strong><span>Valid</span></div><div><strong>1</strong><span>Duplicate</span></div><div><strong class="${state.importBad?'warn':''}">${state.importBad?1:0}</strong><span>Errors / unknown</span></div></div>
 ${notice(state.importBad?'<strong>Unknown instrument: XXXX.</strong> Resolve this row before confirming the import. No rows will be committed while validation fails.':'<strong>13 LOTS → 1,300 SHARES.</strong> Quantities are normalized once. The existing transaction is marked as a duplicate and will not be added again.',state.importBad?'warning':'info',state.importBad?'warning':'info')}
 <div class="table-scroll" style="margin-top:17px"><table style="min-width:440px"><thead><tr><th>Row / instrument</th><th>Type</th><th class="num">Input</th><th class="num">Normalized</th><th>Validation</th></tr></thead><tbody><tr><td>1 · Cash</td><td>Deposit</td><td class="num">Rp20,000,000</td><td class="num">—</td><td>${badge('Valid','match','check')}</td></tr><tr><td>2 · BBCA</td><td>Buy</td><td class="num">13 LOTS</td><td class="num">1,300 shares</td><td>${badge('Valid','match','check')}</td></tr><tr><td>3 · BBRI</td><td>Buy</td><td class="num">500 SHARES</td><td class="num">500 shares</td><td>${badge('Valid','match','check')}</td></tr><tr><td>4 · TLKM</td><td>Buy</td><td class="num">5 LOTS</td><td class="num">500 shares</td><td>${badge('Duplicate','outline','history')}</td></tr><tr><td>5 · ${state.importBad?'XXXX':'ANTM'}</td><td>Buy</td><td class="num">3 LOTS</td><td class="num">300 shares</td><td>${state.importBad?badge('Unknown','unknown','unknown'):badge('Valid','match','check')}</td></tr></tbody></table></div>
 <p class="muted" style="font-size:10px;margin:13px 0">${state.importBad?'3 valid new rows; the batch is blocked.':'4 new events · 1 duplicate skipped'} · fixed synthetic illustration, not validation of a selected file</p>
 <div class="import-actions"><button class="button ghost" data-action="back-import">Back to file</button><button class="button primary" data-action="confirm-import" ${state.importBad?'disabled':''}>Confirm Import ${icon('arrow')}</button></div><p class="muted" style="font-size:10px;margin-top:15px">${icon('lock')} Preview writes nothing. Confirmation is always an explicit action.</p>`;
}
function designSystem() {
 const colors=[['Canvas','--bg'],['Surface','--surface'],['Raised surface','--surface-raised'],['Accent','--accent'],['Positive','--positive'],['Negative','--negative'],['Review / warning','--warning'],['Missing holding','--missing'],['Data information','--info']];
 return pageHeader('A REUSABLE VISUAL LANGUAGE','Design system','Quiet surfaces. Precise numbers. States that carry meaning.',`<button class="button" data-action="theme">${icon('sun')}Switch theme</button>`)+
 `<section class="panel kit-panel state-gallery"><h2>Interaction & state references</h2><p class="muted">Open a synthetic example to inspect the intended behavior.</p><div class="gallery-row"><span>Reconciliation</span><div class="wrap">${['review','match','empty','loading','error'].map(s=>`<button class="button" data-demo-reconcile="${s}">${s[0].toUpperCase()+s.slice(1)}</button>`).join('')}</div></div><div class="gallery-row"><span>Import validation</span><div class="wrap"><button class="button" data-demo-import="csv-ready">CSV ready</button><button class="button" data-demo-import="csv-invalid">Unknown instrument</button><button class="button" data-demo-import="json-ready">JSON restore</button><button class="button" data-demo-import="json-invalid">Occupied destination</button></div></div></section><div class="kit-grid"><section class="panel kit-panel"><h2>Semantic colors</h2><div class="token-swatches">${colors.map(([name,token])=>`<div><div class="swatch" style="background:var(${token})"></div><small>${name}</small><code>${token}</code></div>`).join('')}</div></section><section class="panel kit-panel"><h2>Type & numerical hierarchy</h2><div class="stack"><h1>Know what you hold.</h1><h2>Clear records. Considered decisions.</h2><p class="secondary">13 px body copy for compact, readable product surfaces.</p><p class="muted" style="font-size:11px">11 px labels and table headers. Muted does not mean invisible.</p><p class="number" style="font-size:30px;letter-spacing:-1px">Rp 8,750,000<span class="positive" style="font-size:15px;margin-left:20px">+3.28%</span></p><p class="mono muted">TABULAR NUMERALS / IMMUTABLE REFERENCES</p></div></section>
 <section class="panel kit-panel"><h2>States, never color alone</h2><div class="wrap">${['MATCH','REVIEW','MISSING_FROM_LEDGER','MISSING_FROM_EXPECTED','UNKNOWN_INSTRUMENT'].map(statusBadge).join('')}${badge('Degraded quality','degraded','layers')}${badge('Stale · 29 Sep','info','clock')}${badge('Unavailable price','unknown','unknown')}${badge('−Rp325,000','danger')}${badge('Inactive version','outline','history')}</div><p class="muted" style="margin-top:20px;font-size:11px">Amber marks a discrepancy, not a loss. Violet marks a missing record. Red is reserved for losses, errors and destructive intent.</p></section>
 <section class="panel kit-panel"><h2>Actions & controls</h2><div class="wrap" style="margin-bottom:22px"><button class="button primary" data-page="reconcile">Compare Portfolio ${icon('arrow')}</button><button class="button" data-page="import">Export Portfolio</button><button class="button danger" data-action="invalidate-thesis">Invalidate</button><button class="button" disabled>Confirm Import</button></div><div class="fields"><label class="field"><span>Input label</span><input placeholder="An example field"></label><label class="field"><span>Mandate</span><select class="control"><option>INVEST</option><option>FAST_SWING</option><option>LONG_SWING</option></select></label></div></section>
 <section class="panel kit-panel"><h2>Empty & loading</h2><div class="empty-state" style="padding:12px">${icon('journal')}<h3>No thesis recorded yet</h3><p>Document your own reasoning by creating the first version.</p></div><div class="skeleton-row" aria-label="Example loading placeholders">${'<div class="skeleton"></div>'.repeat(5)}</div></section><section class="panel kit-panel"><h2>Errors & incomplete data</h2><div class="stack">${notice('<strong>Comparison unavailable.</strong> Your inputs remain here. Try again.','error','warning')}${notice('<strong>5 of 6 holdings priced.</strong> Total portfolio value is unavailable.','info','info')}${notice('A correction creates a new event; the original stays in history.','','history')}</div></section></div>
 <div class="section-heading"><h2>Layout rhythm</h2><span class="muted">4 px base · 8 / 12 / 16 / 20 / 24 / 32 / 40 spacing</span></div>${notice('8 px panel radius, 5 px control radius, 1 px borders. Elevation is reserved for modal dialogs. Standard screens use alignment and space to establish hierarchy.','','palette')}`;
}
function render() {
 nav();$('#main').innerHTML=({reconcile:reconciliation,portfolio,overview:portfolio,transactions:transactionPage,thesis:thesisPage,import:importPage,system:designSystem}[state.page]||reconciliation)();
 $('#sidebar').classList.remove('open');$('[data-action="menu"]').setAttribute('aria-expanded','false');
}
function navigate(page) { if(!['reconcile','portfolio','overview','transactions','thesis','import','system'].includes(page))return; state.page=page; if(location.hash!=='#'+page)history.replaceState(null,'','#'+page);render();window.scrollTo(0,0);$('#main').focus({preventScroll:true}); }
function openDialog(content) { const dialog=$('#dialog');dialog.innerHTML=content;dialog.showModal(); }
function closeDialog() { $('#dialog').close(); }
function qualityDialog(symbol) {
 const items=symbol?ledger.filter(h=>h.symbol===symbol):ledger;
 openDialog(`<div class="dialog-head"><div><p class="eyebrow">DATA CONTEXT</p><h2 id="dialog-title">${symbol?esc(symbol)+' · market data':'Freshness & quality'}</h2><p>Source dates stay attached to every price.</p></div><button class="icon-button" data-action="close-dialog" aria-label="Close data details">${icon('close')}</button></div><div class="dialog-body"><div class="stack">${items.map(h=>`<div class="file-selected">${symbolCell(h.symbol)}<div style="margin-left:auto;text-align:right">${badge(h.quality,h.kind==='review'?'degraded':h.kind,h.kind==='review'?'layers':'')}<small>${h.price==null?'No current market price':`Rp${number(h.price)} · raw close · synthetic fixture`}</small></div></div>`).join('')}${notice('Freshness and data quality are separate from P/L and reconciliation status. An unavailable price is not zero.','info','info')}</div></div><div class="dialog-footer"><button class="button" data-action="close-dialog">Done</button></div>`);
}
function resetSnapshot(match=false) { state.expected=match?ledger.map(({symbol,shares,avg})=>({symbol,shares,avg})):defaultExpected();state.cash=match?ledgerCash:8700000;state.through='2026-09-30';state.cutoff='2026-10-01T08:00';state.error='';state.resultFilter='all';state.scenario=match?'match':'review';state.editorOpen=false;state.result=compareSnapshot(); }
function invalidateComparison() { $('#snapshot-caption').innerHTML=`${state.expected.length} holdings · Expected cash <strong>Rp${Number.isFinite(state.cash)?number(state.cash):'—'}</strong>`;state.result=null;state.scenario='review';state.error='';$('#snapshot-error').hidden=true;$('#reconcile-result').innerHTML=reconcileResult(); }
function compare() {
 const form=$('#snapshot-form');if(!form.reportValidity())return;
 try {
  if(state.through!=='2026-09-30'||state.cutoff!=='2026-10-01T08:00')throw new Error('This design preview contains one historical fixture: 30 Sep 2026, known by 01 Oct 2026 at 08:00 WIB. Reset the example to compare. The live app will query both selected dates.');
  if(!Number.isFinite(state.cash)||state.cash<0||state.cash>1e12)throw new Error('Expected cash must be a nonnegative amount.');
  state.result=compareSnapshot();state.error='';state.scenario='review';state.resultFilter='all';$('#snapshot-error').hidden=true;$('#reconcile-result').innerHTML=reconcileResult();toast('Comparison complete. Your ledger has not changed.');
 } catch(error) { state.result=null;state.error=error.message;$('#snapshot-error').textContent=error.message;$('#snapshot-error').hidden=false;$('#reconcile-result').innerHTML=reconcileResult(); }
}
function invalidateImport(){state.importStep=1;state.importBad=false;}
function chooseFile(file) {
 if(!file)return;invalidateImport();const error=$('#file-error');
 if(file.size>8*1024*1024||!file.name.toLowerCase().endsWith(state.importFormat==='JSON'?'.json':'.csv')) {state.fileName='';error.textContent=`Select a ${state.importFormat} file no larger than 8 MiB.`;error.hidden=false;$('[data-action="preview-import"]').disabled=true;return;}
 // Intentionally retain only the display name: a design reference never needs private file contents.
 state.fileName=file.name;render();
}
document.addEventListener('click',event=>{
 const target=event.target.closest('button, a, [data-action]');if(!target)return;
 if(target.dataset.page){event.preventDefault();navigate(target.dataset.page);return;}
 if(target.dataset.resultFilter){state.resultFilter=target.dataset.resultFilter;$('#reconcile-result').innerHTML=reconcileResult();$(`[data-result-filter="${state.resultFilter}"]`).focus();return;}
 if(target.dataset.transactionFilter){state.transactionFilter=target.dataset.transactionFilter;render();$(`[data-transaction-filter="${state.transactionFilter}"]`).focus();return;}
 if(target.dataset.thesisSymbol){state.thesisSymbol=target.dataset.thesisSymbol;render();return;}
 if(target.dataset.importFormat){invalidateImport();state.importFormat=target.dataset.importFormat;state.fileName='';state.importBad=false;render();return;}
 if(target.dataset.demoReconcile){const value=target.dataset.demoReconcile;resetSnapshot(value==='match');state.scenario=value;if(value==='empty'){state.result=null;state.editorOpen=true;}navigate('reconcile');return;}
 if(target.dataset.demoImport){const [format,validation]=target.dataset.demoImport.split('-');state.importFormat=format.toUpperCase();state.importStep=2;state.importBad=validation==='invalid';state.fileName='synthetic-'+(format==='csv'?'transactions.csv':'portfolio-backup.json');navigate('import');return;}
 const action=target.dataset.action;
 if(action==='menu'){const open=$('#sidebar').classList.toggle('open');target.setAttribute('aria-expanded',String(open));}
 if(action==='theme'){const light=document.documentElement.dataset.theme!=='light';document.documentElement.dataset.theme=light?'light':'dark';$('[data-action="theme"]').setAttribute('aria-label',`Switch to ${light?'dark':'light'} theme`);}
 if(action==='quality'||action==='holding')qualityDialog(target.dataset.symbol);
 if(action==='design-system')navigate('system');
 if(action==='close-dialog')closeDialog();
 if(action==='toggle-snapshot'){state.editorOpen=!state.editorOpen;$('#snapshot-editor').hidden=!state.editorOpen;target.setAttribute('aria-expanded',String(state.editorOpen));target.innerHTML=(state.editorOpen?'Hide inputs':'Edit snapshot')+' '+icon('chevron');if(state.editorOpen)$('#through').focus();}
 if(action==='reset-snapshot'){resetSnapshot();render();toast('Synthetic example restored.');}
 if(action==='retry-compare')compare();
 if(action==='add-holding'){if(state.expected.length>=20){toast('This visual example supports up to 20 input rows.');return;}state.expected.push({symbol:'',shares:'',avg:''});$('#expected-rows').innerHTML=expectedRows();$('#expected-count').textContent=`${state.expected.length} holdings entered`;invalidateComparison();$(`[data-row="${state.expected.length-1}"][data-field="symbol"]`).focus();}
 if(action==='remove-holding'){state.expected.splice(Number(target.dataset.row),1);$('#expected-rows').innerHTML=expectedRows();$('#expected-count').textContent=`${state.expected.length} holdings entered`;invalidateComparison();$('[data-action="add-holding"]').focus();}
 if(action==='correct')correctionDialog(target.dataset.event);
 if(action==='new-thesis'||action==='invalidate-thesis')thesisDialog(action==='invalidate-thesis');
 if(action==='sample-file'){state.fileName=state.importFormat==='JSON'?'synthetic-portfolio-backup.json':'synthetic-transactions.csv';state.importBad=false;render();}
 if(action==='preview-import'&&state.fileName){state.importStep=2;render();}
 if(action==='back-import'){state.importStep=1;render();}
 if(action==='confirm-import'&&!state.importBad&&state.importStep===2){state.importStep=3;render();toast('Explicit confirmation demonstrated. No data was imported.');}
 if(action==='restart-import'){state.importStep=1;state.fileName='';render();}
 if(action==='export-demo')toast('Export preview: the live app downloads a lossless JSON backup. No real portfolio is connected here.');
});
document.addEventListener('input',event=>{
 const el=event.target;
 if(el.dataset.field){const row=state.expected[Number(el.dataset.row)];row[el.dataset.field]=el.dataset.field==='symbol'?el.value:Number(el.value);invalidateComparison();}
 if(el.id==='through'||el.id==='cutoff'){state[el.id]=el.value;invalidateComparison();}
 if(el.id==='expected-cash'){state.cash=el.value.trim()?Number(el.value.replaceAll(',','')):NaN;invalidateComparison();}
 if(el.id==='transaction-search'){state.transactionSearch=el.value;$('#transaction-rows').innerHTML=transactionRows();}
});
document.addEventListener('focusin',event=>{if(event.target.id==='expected-cash'&&Number.isFinite(state.cash))event.target.value=String(state.cash);});
document.addEventListener('focusout',event=>{if(event.target.id==='expected-cash'&&event.target.value.trim()&&Number.isFinite(state.cash))event.target.value=number(state.cash);});
document.addEventListener('change',event=>{
 const el=event.target;
 if(el.id==='restore-mode'){state.restoreMode=el.value;invalidateImport();}
 if(el.id==='portfolio-select'){invalidateImport();state.fileName='';if(state.page==='import')render();}
 if(el.id==='import-file')chooseFile(el.files[0]);
});
document.addEventListener('submit',event=>{
 event.preventDefault();const form=event.target;
 if(form.id==='snapshot-form')compare();
 if(form.id==='correction-form') {
  const f=Object.fromEntries(new FormData(form)), original=transactions.find(t=>t.id===form.dataset.event);
  const duplicate=transactions.some(t=>t.ref===f.reference);if(duplicate){form.elements.reference.setCustomValidity('Use a new external reference for the correction.');form.elements.reference.reportValidity();form.elements.reference.addEventListener('input',()=>form.elements.reference.setCustomValidity(''),{once:true});return;}
  const correction={...original,id:'evt-demo-'+(transactions.length+1),type:f.type,quantity:original.symbol?Number(f.quantity):null,price:original.symbol?Number(f.price):null,cash:original.symbol?undefined:Number(f.cash),fees:Number(f.fees),ref:f.reference,note:f.note,trade:new Intl.DateTimeFormat('en-GB',{day:'2-digit',month:'short',year:'numeric',timeZone:'UTC'}).format(new Date(f.date+'T00:00:00Z')),recorded:'01 Oct, 07:59',source:'Manual',status:'Active',supersedes:original.id};
  original.status='Superseded';transactions.splice(transactions.indexOf(original)+1,0,correction);closeDialog();render();($(`[data-event="${correction.id}"]`)||$('#main')).focus();toast('Example correction appended. The original entry is preserved.');
 }
 if(form.id==='thesis-form'){
  const f=Object.fromEntries(new FormData(form)),invalidate=form.dataset.invalidate==='true',original=state.theses[state.thesisSymbol]?.[0];
  state.theses[state.thesisSymbol] ??= [];
  state.theses[state.thesisSymbol].unshift({version:(original?.version||0)+1,mandate:invalidate?original.mandate:f.mandate,active:!invalidate,date:'01 Oct 2026, 07:59 WIB',text:f.text,invalidation:f.invalidation});closeDialog();state.page='thesis';render();$('[data-action="new-thesis"]').focus();toast('A new example version was appended. Earlier versions remain intact.');
 }
});
document.addEventListener('dragover',event=>{if(event.target.closest('#drop-zone')){event.preventDefault();$('#drop-zone').classList.add('dragover');}});
document.addEventListener('dragleave',event=>{if(event.target.closest('#drop-zone'))$('#drop-zone').classList.remove('dragover');});
document.addEventListener('drop',event=>{if(event.target.closest('#drop-zone')){event.preventDefault();chooseFile(event.dataTransfer.files[0]);}});
// Native dialog supplies Escape dismissal and focus restoration; Tab also wraps at its edges.
$('#dialog').addEventListener('click',event=>{if(event.target===$('#dialog')){const b=event.target.getBoundingClientRect();if(event.clientX<b.left||event.clientX>b.right||event.clientY<b.top||event.clientY>b.bottom)closeDialog();}});
document.addEventListener('keydown',event=>{
 if(event.key==='Tab'&&$('#dialog').open){
  const controls=$$('button:not(:disabled),input:not(:disabled),select:not(:disabled),textarea:not(:disabled),a[href],[tabindex="0"]',$('#dialog')).filter(e=>e.getClientRects().length);
  const first=controls[0],last=controls.at(-1),active=document.activeElement;
  if((event.shiftKey&&active===first)||(!event.shiftKey&&active===last)||!$('#dialog').contains(active)){event.preventDefault();(event.shiftKey?last:first)?.focus();}
 }
 if(event.key==='Escape'){$('#sidebar').classList.remove('open');$('[data-action="menu"]').setAttribute('aria-expanded','false');}
 const tab=event.target.closest('[role="tab"]');if(tab&&['ArrowLeft','ArrowRight','Home','End'].includes(event.key)){
  event.preventDefault();const tabs=$$('[role="tab"]',tab.parentElement);const index=tabs.indexOf(tab);const next=event.key==='Home'?0:event.key==='End'?tabs.length-1:(index+(event.key==='ArrowRight'?1:-1)+tabs.length)%tabs.length;tabs[next].click();
 }
});
window.addEventListener('hashchange',()=>navigate(location.hash.slice(1)||'reconcile'));
$('#portfolio-glyph').innerHTML=icon('portfolio');$('[data-action="theme"]').innerHTML=icon('sun');$('[data-action="menu"]').innerHTML=icon('menu');
if(['overview','portfolio','transactions','thesis','reconcile','import','system'].includes(location.hash.slice(1)))state.page=location.hash.slice(1);
render();
