<Project Sdk="Microsoft.NET.Sdk.Web">
  <PropertyGroup>
    <RunWorkingDirectory>$(MSBuildProjectDirectory)/../..</RunWorkingDirectory>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="../IdxStockIntelligence.Infrastructure/IdxStockIntelligence.Infrastructure.csproj" />
  </ItemGroup>
</Project>
