import { useEffect, useState, type MouseEvent, type ReactNode } from 'react';
import { Badge, Empty, LoadingSkeleton, Metric, Notice, PageHeader } from './ui.js';
import { Facts, Reasons, Availability, ProvenanceDetails } from './ScreenerPage.js';
import { StockLink } from './StocksPage.js';
import { number } from './screener.js';
import { recorded } from './view.js';
import { abbreviatedHash, decisionRoute, decisionSetup, DecisionSession, type DecisionHeader, type DecisionHistoryItem, type DecisionPage, type DecisionRow, type DecisionRun, type DecisionState } from './decisions.js';

export function DecisionLink({id,children,onNavigate}:{id:string;children:ReactNode;onNavigate?:(id:string)=>void}) {
 return <a className="text-button stock-link break-word" href={decisionRoute(id)} onClick={(e:MouseEvent<HTMLAnchorElement>)=>{if(onNavigate&&!e.ctrlKey&&!e.metaKey&&!e.shiftKey&&!e.altKey&&e.button===0){e.preventDefault();onNavigate(id);}}}>{children}</a>;
}
const status = (h:DecisionHeader) => <Badge kind={h.status==='COMPLETE'?'outline':'unknown'}>{h.status}</Badge>;
const portfolio = (h:DecisionHeader) => h.portfolioId ? `Portfolio ${h.portfolioId}` : 'Discovery only · no portfolio context';
export function DecisionListResults({state,onNavigate}:{state:DecisionState<DecisionPage<DecisionHeader>>;onNavigate?:(id:string)=>void}) {
 if(state.busy)return <LoadingSkeleton label="Loading retained decision captures…"/>;
 if(state.error)return <Notice kind="error">Decision history unavailable: {state.error}</Notice>;
 if(!state.result?.items.length)return <Empty title="No retained captures">Prospective captures appear here after the operational capture workflow records them.</Empty>;
 return <div className="panel table-scroll" tabIndex={0} aria-label="Recent decision captures; scroll horizontally"><table className="decision-list-table"><caption className="sr-only">Retained prospective captures in backend order; captured status is not an application error</caption><thead><tr>{['Captured at · WIB','Target session','Through','Captured status','Policy','Universe','Portfolio context','Rows','Input hash','Run ID'].map(t=><th key={t} scope="col">{t}</th>)}</tr></thead><tbody>{state.result.items.map(h=><tr key={h.runId}><td><time dateTime={h.capturedAt} title={h.capturedAt}>{recorded(h.capturedAt)}</time></td><td>{h.targetSession??'Unavailable'}</td><td>{h.through}</td><td>{status(h)}</td><td>{h.policyId}</td><td>{h.universe}</td><td>{portfolio(h)}</td><td className="num">{h.rowCount}</td><td className="mono" title={h.inputHash}>{abbreviatedHash(h.inputHash)}</td><td><DecisionLink id={h.runId} onNavigate={onNavigate}>{h.runId}</DecisionLink></td></tr>)}</tbody></table></div>;
}
export function DecisionHistory({onNavigate}:{onNavigate:(id:string)=>void}) {
 const [cursor,setCursor]=useState<string|null>(null),[reload,setReload]=useState(0);
 const [state,setState]=useState<DecisionState<DecisionPage<DecisionHeader>>>({result:null,busy:true,error:''});
 const [session]=useState(()=>new DecisionSession(setState));
 useEffect(()=>{void session.load('/screener/decision-snapshots'+(cursor?'?'+new URLSearchParams({cursor}):''));return()=>session.invalidate();},[session,cursor,reload]);
 return <div className="page-stack decisions-page"><PageHeader eyebrow="RETAINED RESEARCH · READ ONLY" title="Decision History" subtitle="Immutable prospective captures, ordered by capture time. Captured facts remain separate from current research."/><DecisionListResults state={state} onNavigate={onNavigate}/><div className="panel panel-body wrap" aria-label="Decision history pagination"><span>Up to 20 captures per page · backend cursor order</span><button className="button" disabled={state.busy||!state.result?.nextCursor} onClick={()=>setCursor(state.result!.nextCursor)}>Next page</button><button className="button ghost" disabled={state.busy} onClick={()=>{setCursor(null);setReload(n=>n+1);}}>Reset to latest</button></div></div>;
}
export function CapturedRowDetails({row,universeKnown,onOpenStock}:{row:DecisionRow;universeKnown:boolean;onOpenStock?:(id:string)=>void}) {
 const r=row.result;
 return <section id="captured-row-detail" className="panel panel-body page-stack" aria-label={`Captured details for ${row.symbol??row.instrumentId}`}><h2>Captured instrument · {row.symbol??'Unavailable symbol'}</h2>
  {!row.configured&&<Notice>{universeKnown?'Outside configured Screener scope':'Configured membership was unknown at capture'}{row.held?' · Held at capture':''}. Setup evaluation remains {row.setupEvaluated?'evaluated':'not evaluated'}.</Notice>}
  <Facts values={{'Instrument ID':row.instrumentId,'Captured symbol':row.symbol,Configured:row.configured,Held:row.held,'Discovery rank':row.discoveryRank}}/>
  <section><h3>Eligibility · {row.eligibility}</h3><Reasons values={r.eligibilityReasons}/></section>
  <section><h3>Setup · {decisionSetup(row)}</h3><p>Evaluated: {row.setupEvaluated?'Yes':'No'}</p><Reasons values={r.setupReasons}/></section>
  <section><h3>Captured episode</h3>{r.episode?<><p>Captured row state: {decisionSetup(row)}</p><Facts values={{'Episode ID':row.episodeId,...r.episode}}/></>:<p>No captured episode.</p>}</section>
  <section><h3>Captured market and technical values</h3><p className="muted">Full returned values; no frontend calculations.</p><Facts values={{'Market date':row.marketDate,Close:row.close,'Prior high20':r.priorHigh20,'Distance to prior high · %':r.distanceToHighPercent,EMA20:r.ema20,EMA50:r.ema50,ATR14:r.atr14,'ATR · %':r.atrPercent,'Volume ratio20':r.volumeRatio20,'RS20 · pp':r.rs20Pp,'RS60 · pp':r.rs60Pp,Trend:r.trend,'Prior-20 monetary proxy · IDR':r.monetaryLiquidity20Idr,Stale:r.stale,'No trade':r.noTrade,'Trading status':r.tradingStatus}}/></section>
  <Availability fields={r.fieldStates}/><p className="muted">A populated feature with no availability entry was AVAILABLE at capture.</p>
  <section><h3>Captured data state · {r.dataQuality}</h3><Reasons values={r.dataReasons}/></section>
  <section><h3>Captured portfolio facts</h3><Facts values={{Shares:row.shares,'Invested cost':row.investedCost,'Average cost':row.averageCost,Mandate:row.mandate,'Thesis version ID':row.thesisVersionId,'Thesis version':row.thesisVersion,'Thesis active':row.thesisActive}}/></section>
  <ProvenanceDetails value={r.provenance}/><StockLink id={row.instrumentId} onNavigate={onOpenStock}>Open current Stock Detail</StockLink><p className="muted">Current Stock Detail may contain newer information. These captured values remain unchanged.</p>
 </section>;
}
export function DecisionDetailResults({run,onOpenStock}:{run:DecisionRun;onOpenStock?:(id:string)=>void}) {
 const [selected,setSelected]=useState<string|null>(null);const h=run.header,s=run.result.summary,c=run.result.marketContext;
 const row=run.rows.find(r=>r.instrumentId===selected);
 return <>
  <Notice><strong>Captured status {status(h)}</strong> · Stored factual evaluation. BLOCKED means required evidence was unavailable at capture.</Notice>
  <section className="panel panel-body page-stack" aria-label="Immutable capture context"><h2>Immutable capture context</h2><p>{portfolio(h)}</p><Facts values={{'Run ID':h.runId,'Request ID':h.requestId,'Captured at':h.capturedAt,'Known by':h.knowledgeCutoff,Through:h.through,'Target market session':h.targetSession,'Recorded at':h.recordedAt,'History anchor':h.historyAnchor,'Policy ID':h.policyId,Universe:h.universe,'Universe snapshot ID':h.universeSnapshotId,'Schema version':h.schemaVersion,'Capture kind':h.captureKind,'Portfolio ID':h.portfolioId,'Row count':h.rowCount}}/><p className="muted">Captured at is when this prospective evaluation occurred. Known by is its knowledge boundary. Through is its market-date boundary. Target market session is the session evaluated and may be earlier. Recorded at is the database insertion time. Timestamps above are exact UTC.</p></section>
  <div className="summary-strip screener-metrics">{([['Configured',s.configured],['Eligible',s.eligible],['Data Blocked',s.dataBlocked],['Candidates',s.candidates],['Held',s.held]] as const).map(([label,value])=><Metric key={label} label={label} value={value??'Unavailable'} note="Captured count"/>)}</div><Reasons values={run.result.reasons}/>
  <section className="panel panel-body page-stack" aria-label="Captured market context"><h2>Captured market context</h2><Facts values={{'Benchmark ID':c.instrumentId,'Market date':c.marketDate,'Close · index points':c.close,Trend:c.trend,Volatility:c.volatility,EMA20:c.ema20,EMA50:c.ema50,ATR14:c.atr14,'ATR · %':c.atrPercent}}/><Reasons values={c.reasons}/><Availability fields={c.fieldStates}/><details><summary>Captured benchmark provenance</summary><ProvenanceDetails value={c.provenance}/></details></section>
  <section className="panel" aria-label="Captured instrument population"><div className="panel-body"><h2>Captured population · {h.rowCount} rows</h2><p>Every persisted instrument in returned order, including blocked and held rows. No shortlist filter.</p></div>{run.rows.length?<div className="table-scroll" tabIndex={0} aria-label="Captured population; scroll horizontally"><table className="decision-rows-table"><caption className="sr-only">All persisted captured instrument rows; null values are unavailable</caption><thead><tr>{['Captured symbol','Configured','Held','Eligibility','Setup','Evaluated','Market date','Close','Distance · %','RS20 · pp','RS60 · pp','Trend'].map(t=><th key={t} scope="col">{t}</th>)}</tr></thead><tbody>{run.rows.map(r=><tr key={r.instrumentId} data-instrument-id={r.instrumentId}><td><button className="text-button" aria-expanded={selected===r.instrumentId} aria-controls="captured-row-detail" onClick={()=>setSelected(selected===r.instrumentId?null:r.instrumentId)}>{r.symbol??r.instrumentId}</button>{!r.configured&&<small className="amount-secondary">{h.universeSnapshotId===null?'Membership unknown':'Outside configured scope'}</small>}</td><td>{r.configured?'Yes':'No'}</td><td>{r.held?'Yes':'No'}</td><td>{r.eligibility}</td><td>{decisionSetup(r)}</td><td>{r.setupEvaluated?'Yes':'No'}</td><td>{r.marketDate??'Unavailable'}</td><td className="num">{number(r.close)}</td><td className="num">{number(r.result.distanceToHighPercent)}</td><td className="num">{number(r.result.rs20Pp)}</td><td className="num">{number(r.result.rs60Pp)}</td><td>{r.result.trend}</td></tr>)}</tbody></table></div>:<p className="panel-body">No instruments were captured. No rows are synthesized.</p>}</section>
  {row&&<CapturedRowDetails row={row} universeKnown={h.universeSnapshotId!==null} onOpenStock={onOpenStock}/>}
  <section className="panel panel-body page-stack" aria-label="Captured evidence linkage"><h2>Evidence linkage</h2><Facts values={{Policy:h.policyId,'Universe snapshot':h.universeSnapshotId,'Row count':h.rowCount,'Captured status':h.status}}/><p>Input hash</p><pre className="decision-hash" tabIndex={0}>{h.inputHash}</pre><p>Selected digest</p><pre className="decision-hash" tabIndex={0}>{h.selectedDigest}</pre><p className="muted">Retained linkage identifiers. Reproducibility verification is a separate future workflow.</p></section>
 </>;
}
export function DecisionDetail({id,onNavigate,onOpenStock}:{id:string;onNavigate:(id:string)=>void;onOpenStock:(id:string)=>void}) {
 const [state,setState]=useState<DecisionState<DecisionRun>>({result:null,busy:true,error:''}),[reload,setReload]=useState(0);
 const [session]=useState(()=>new DecisionSession(setState));
 useEffect(()=>{void session.load('/screener/decision-snapshots/'+encodeURIComponent(id),id);return()=>session.invalidate();},[id,session,reload]);
 return <div className="page-stack decisions-page"><PageHeader eyebrow="IMMUTABLE CAPTURE · READ ONLY" title="Decision Detail" subtitle="Only retained capture facts are shown here."/><DecisionLink id="" onNavigate={onNavigate}>Back to Decision History</DecisionLink>{state.busy&&<LoadingSkeleton label="Loading retained decision capture…"/>}{state.error&&<><Notice kind="error">{state.error}</Notice><button className="button" onClick={()=>setReload(n=>n+1)}>Retry read</button></>}{state.result&&<DecisionDetailResults key={state.result.header.runId} run={state.result} onOpenStock={onOpenStock}/>}</div>;
}
export function InstrumentDecisions({id,onNavigate}:{id:string;onNavigate?:(id:string)=>void}) {
 const [state,setState]=useState<DecisionState<DecisionPage<DecisionHistoryItem>>>({result:null,busy:true,error:''});
 const [session]=useState(()=>new DecisionSession(setState));
 useEffect(()=>{void session.load('/instruments/'+encodeURIComponent(id)+'/decision-snapshots?limit=5',id);return()=>session.invalidate();},[id,session]);
 return <section className="panel panel-body page-stack" aria-label="Instrument decision history"><h2>Decision history</h2><p className="muted">Latest five retained captures for this stable instrument. Captured facts are independent of the current Stock Detail context.</p>{state.busy?<LoadingSkeleton label="Loading instrument decision history…"/>:state.error?<Notice kind="review">Decision history unavailable: {state.error}</Notice>:state.result?.items.length?<div className="table-scroll" tabIndex={0}><table className="decision-list-table"><caption className="sr-only">Latest bounded captured history for this stable instrument</caption><thead><tr>{['Captured at · WIB','Target session','Eligibility','Setup','Captured close','Run status','Capture'].map(t=><th scope="col" key={t}>{t}</th>)}</tr></thead><tbody>{state.result.items.map(({header:h,row:r})=><tr key={h.runId}><td><time dateTime={h.capturedAt} title={h.capturedAt}>{recorded(h.capturedAt)}</time></td><td>{h.targetSession??'Unavailable'}</td><td>{r.eligibility}</td><td>{decisionSetup(r)}</td><td className="num">{number(r.close)}</td><td>{status(h)}</td><td><DecisionLink id={h.runId} onNavigate={onNavigate}>Open capture</DecisionLink></td></tr>)}</tbody></table></div>:<p>No retained captures for this instrument.</p>}</section>;
}
