import React, { useEffect, useRef, useState } from 'react';
import { createRoot } from 'react-dom/client';
import { api, errorMessage } from './api';
import { readDraft } from './reconciliationDraft';
import { loadInstruments as readInstruments } from './instrumentRegistration';
import { coverageLabel, cutoffIso, jakartaToday, money, recorded, valuationLabel, type Holding, type Instrument, type PortfolioView } from './view';
import { ImportPanel } from './ImportPanel';
import { PortfolioTable } from './PortfolioTable';
import { ReconciliationPanel } from './ReconciliationPanel';
import { Screener } from './ScreenerPage';
import { Stocks, StockDetail, StockLink } from './StocksPage';
import { Transactions } from './Transactions';
import { ThesisJournal } from './ThesisJournal';
import { Badge, Dialog, Empty, Icon, LoadingSkeleton, Metric, Navigation, Notice, PageHeader, pages } from './ui';
import './style.css';
function App() {
 const [id,setId]=useState(localStorage.getItem('idx-portfolio-id')??''),[openId,setOpenId]=useState(id),[view,setView]=useState<PortfolioView|null>(null),[instruments,setInstruments]=useState<Instrument[]>([]);const [page,setPage]=useState(()=>location.pathname.startsWith('/stocks')?'stocks':'portfolio'),[stockId,setStockId]=useState(()=>location.pathname.startsWith('/stocks/')?location.pathname.slice(8):''),[menu,setMenu]=useState(false),[theme,setTheme]=useState(localStorage.getItem('idx-theme')??'dark');const [through,setThrough]=useState(()=>readDraft(id)?.through??jakartaToday()),[cutoff,setCutoff]=useState(()=>readDraft(id)?.cutoff??''),[draftThrough,setDraftThrough]=useState(through),[draftCutoff,setDraftCutoff]=useState(cutoff);const [busy,setBusy]=useState(false),[error,setError]=useState(''),[notice,setNotice]=useState(''),[revision,setRevision]=useState(0);const [dialog,setDialog]=useState<'portfolio'|'register'|Holding|null>(null);const [saving,setSaving]=useState(false),[saveError,setSaveError]=useState('');const main=useRef<HTMLElement>(null),menuButton=useRef<HTMLButtonElement>(null);
 async function loadInstruments() {setInstruments(await readInstruments());}
 useEffect(()=>{void loadInstruments().catch(e=>setError(errorMessage(e)));},[]);
 useEffect(()=>{document.documentElement.dataset.theme=theme;localStorage.setItem('idx-theme',theme);},[theme]);
 useEffect(()=>{if(!id){setView(null);return;}const c=new AbortController();setBusy(true);setError('');void api<PortfolioView>(`/portfolios/${id}?${new URLSearchParams({through,cutoff:cutoffIso(cutoff)})}`,undefined,c.signal).then(next=>{if(!c.signal.aborted){setView(next);localStorage.setItem('idx-portfolio-id',id);}}).catch(e=>{if(!c.signal.aborted){setError(errorMessage(e));setView(null);}}).finally(()=>{if(!c.signal.aborted)setBusy(false);});return ()=>c.abort();},[id,through,cutoff,revision]);
 function openPortfolio(next:string){const draft=readDraft(next);const date=draft?.through??jakartaToday(),time=draft?.cutoff??'';setThrough(date);setDraftThrough(date);setCutoff(time);setDraftCutoff(time);setView(null);setId(next);setOpenId(next);setNotice('');setRevision(n=>n+1);}
 async function saved() {setRevision(n=>n+1);setNotice(cutoff?'Saved. The selected historical cutoff remains unchanged; use Now to see newly recorded history.':'Saved. Original history is preserved.');}
 function navigate(next:string){history.pushState({page:next},'',next==='stocks'?'/stocks':'/');setStockId('');setPage(next);setMenu(false);setNotice('');requestAnimationFrame(()=>main.current?.focus({preventScroll:true}));window.scrollTo(0,0);}
 function openStock(next:string){history.pushState({page:'stocks'},'',`/stocks/${encodeURIComponent(next)}`);setStockId(next);setPage('stocks');setMenu(false);setNotice('');window.scrollTo(0,0);requestAnimationFrame(()=>main.current?.focus({preventScroll:true}));}
 useEffect(()=>{const back=(e:PopStateEvent)=>{setPage(e.state?.page??(location.pathname.startsWith('/stocks')?'stocks':'portfolio'));setStockId(location.pathname.startsWith('/stocks/')?location.pathname.slice(8):'');};window.addEventListener('popstate',back);return()=>window.removeEventListener('popstate',back);},[]);
 const label=pages.find(p=>p[0]===page)?.[1]??'Portfolio';
 return <><a className="skip-link" href="#main">Skip to content</a><aside className={`sidebar ${menu?'open':''}`} aria-label="Workspace navigation"><a className="brand" href="#main" onClick={()=>navigate('portfolio')}><span className="brand-mark"><i/><i/><i/></span><span>idx<span className="brand-second">intelligence</span></span></a><p className="workspace-label">PERSONAL WORKSPACE</p><Navigation page={page} onNavigate={navigate}/><div className="sidebar-bottom"><p className="local-indicator"><span className="dot"/>Local workspace<span className="mono">IDR</span></p><div className="profile"><span className="avatar">P</span><div><strong>Personal portfolio</strong><small>Local, owner-controlled records</small></div></div></div></aside>
 <div className="shell"><div className="topbar"><button ref={menuButton} className="icon-button menu-button" aria-label="Toggle navigation" aria-expanded={menu} onClick={()=>setMenu(!menu)} onKeyDown={e=>{if(e.key==='Escape')setMenu(false);}}><Icon name="menu"/></button><div className="breadcrumb"><span>Workspace</span><span className="slash">/</span><strong>{label}</strong></div><div className="topbar-right"><span className="connection"><span className="dot"/>Local only</span><span className="top-divider"/><button className="icon-button" aria-label={`Switch to ${theme==='dark'?'light':'dark'} theme`} onClick={()=>setTheme(theme==='dark'?'light':'dark')}><Icon name="sun"/></button><span className="avatar small">P</span></div></div>
 {page!=='screener'&&page!=='stocks'&&<form className="context-bar" aria-label="Portfolio and historical context" onSubmit={e=>{e.preventDefault();setThrough(draftThrough);setCutoff(draftCutoff);setRevision(n=>n+1);setNotice('');}}><div className="portfolio-select"><Icon name="portfolio"/><button type="button" className="text-button" onClick={()=>{setSaveError('');setDialog('portfolio');}}>{view?.portfolio.name??'Open portfolio'} <Icon name="chevron"/></button><span className="context-currency">IDR</span></div><label><span className="muted">Through</span><input aria-label="As-of / through date" name="through" type="date" min="1900-01-01" max={jakartaToday()} value={draftThrough} onChange={e=>setDraftThrough(e.target.value)} required/></label><label><span className="muted">Known by · WIB</span><input className="context-time" aria-label="Knowledge cutoff in WIB; blank uses now" aria-describedby="cutoff-help" name="cutoff" type="datetime-local" step="1" value={draftCutoff} onChange={e=>setDraftCutoff(e.target.value)}/><small id="cutoff-help" className="muted">Blank = now</small></label><button className="button ghost" type="button" onClick={()=>{setDraftCutoff('');setCutoff('');setRevision(n=>n+1);}}>Now</button><button className="button" type="submit">Apply</button>{view&&<span className="quality-summary">{view.pricedHoldings}/{view.holdingCount} priced</span>}</form>}
 {page!=='screener'&&page!=='stocks'&&(error||notice)&&<div className="context-feedback">{error?<Notice kind="error">{error}</Notice>:<Notice>{notice}</Notice>}</div>}<main id="main" ref={main} tabIndex={-1} onKeyDown={e=>{if(e.key==='Escape'&&menu){setMenu(false);menuButton.current?.focus();}}}>
 {page==='stocks'?<>{stockId?<StockDetail key={stockId+id} id={stockId} portfolioId={id} portfolioName={view?.portfolio.name} onOpenPortfolio={()=>{setSaveError('');setDialog('portfolio');}}/>:<Stocks onNavigate={openStock}/>}</>:page==='screener'?<Screener key={id} onOpenStock={openStock} portfolioId={id} portfolioName={view?.portfolio.name} onOpenPortfolio={()=>{setSaveError('');setDialog('portfolio');}}/>:page==='import'?<ImportPanel key={id} portfolioId={id||undefined} request={api} onImported={async (next,signal)=>{await loadInstruments();if(!signal?.aborted)openPortfolio(next);}}/>:!id?<><PageHeader eyebrow="PERSONAL WORKSPACE" title="Your portfolio workspace" subtitle="Open an existing portfolio or create an empty account."/><Empty title="No portfolio selected">Choose Open portfolio above. Your history stays local.</Empty></>:busy&&!view?<LoadingSkeleton/>:!view?<Empty title="Portfolio unavailable">Check the selected portfolio and historical context.</Empty>:page==='reconcile'?<ReconciliationPanel key={id} portfolioId={id} through={through} cutoff={cutoff} contextDirty={draftThrough!==through||draftCutoff!==cutoff} onRegistryChanged={loadInstruments}/>:page==='transactions'?<Transactions key={id} portfolioId={id} cutoff={cutoff} instruments={instruments} revision={revision} onSaved={saved}/>:page==='thesis'?<ThesisJournal key={id} portfolioId={id} holdings={view.holdings} cutoff={cutoff} revision={revision} onSaved={saved}/>:<><PageHeader eyebrow="YOUR PORTFOLIO, CLEARLY RECORDED" title={view.portfolio.name} subtitle="Ledger costs and dated market observations, with explicit valuation coverage."><button className="button" onClick={()=>{setSaveError('');setDialog('register');}}><Icon name="plus"/>Register equity</button></PageHeader>
 <div className="summary-strip portfolio-metrics"><Metric label="Portfolio value" value={money(view.totalEquity)} note="IDR · cash + priced positions"/><Metric label="Cash" value={money(view.cash)} note={view.negativeCash?'NEGATIVE CASH':'IDR · ledger balance'}/><Metric label="Invested cost" value={money(view.investedCost)} note="Open positions · weighted cost"/><Metric label="Unrealized P/L" value={money(view.unrealizedPnl)} note={view.unrealizedPnl===null?'Incomplete pricing coverage':'IDR · complete valuation'}/><Metric label="Realized P/L" value={money(view.realizedPnl)} note="Includes closed positions"/><Metric label="Data coverage" value={`${view.pricedHoldings}/${view.holdingCount}`} note={view.valuationCoverage}/></div>
 {view.totalMarketValue===null&&<Notice kind="review"><strong>Valuation is incomplete.</strong> Unpriced holdings stay visible. Priced subtotal: Rp {money(view.pricedMarketValue)}. Complete portfolio value and unrealized P/L are unavailable.</Notice>}{!view.holdings.length?<Empty title="No open holdings">Record a transaction or import generic CSV to add a position.</Empty>:<PortfolioTable holdings={view.holdings} onOpen={h=>setDialog(h)}/>}
 <div className="section-heading"><h2>Valuation notes</h2><span className="muted">{coverageLabel(view)}</span></div><p className="muted">Average cost is reconstructed from the ledger. Market observations retain their original dates and provenance. Missing data is unavailable.</p><div className="record-actions"><button className="button primary" onClick={()=>navigate('transactions')}>View transactions <Icon name="arrow"/></button></div></>}
 {page!=='screener'&&page!=='stocks'&&view&&<p className="read-context muted">Through {view.through} · known by {recorded(view.knowledgeCutoff)} · {busy?'Refreshing…':view.operation}</p>}</main><footer className="workspace-footer"><span><span className="dot"/>LOCAL PORTFOLIO <span className="footer-separator">/</span>Deterministic ledger · IDR</span><span>History stays explicit</span></footer></div>
 {dialog==='portfolio'&&<Dialog title="Open or create portfolio" eyebrow="PERSONAL WORKSPACE" onClose={()=>{if(!saving)setDialog(null);}}><div className="dialog-body page-stack"><form id="open-portfolio-form" onSubmit={e=>{e.preventDefault();setSaving(true);setSaveError('');void api<PortfolioView>(`/portfolios/${openId}`).then(()=>{openPortfolio(openId);setDialog(null);}).catch(e=>setSaveError(errorMessage(e))).finally(()=>setSaving(false));}}><label className="field"><span>Existing portfolio ID</span><input name="portfolioId" value={openId} onChange={e=>setOpenId(e.target.value)} required pattern="[0-9a-fA-F-]{36}"/></label><div className="record-actions"><button className="button" disabled={saving}>Open portfolio</button></div></form>{page!=='stocks'&&<form id="create-portfolio-form" onSubmit={e=>{e.preventDefault();const f=Object.fromEntries(new FormData(e.currentTarget));setSaving(true);setSaveError('');void api<{id:string}>('/portfolios',{name:f.name}).then(p=>{openPortfolio(p.id);setDialog(null);}).catch(e=>setSaveError(errorMessage(e))).finally(()=>setSaving(false));}}><label className="field"><span>New portfolio name</span><input name="name" required maxLength={200}/></label><div className="record-actions"><button className="button primary" disabled={saving}>Create empty portfolio</button></div></form>}{saveError&&<Notice kind="error">{saveError}</Notice>}</div><div className="dialog-footer"><button className="button ghost" disabled={saving} onClick={()=>setDialog(null)}>Cancel</button></div></Dialog>}
 {dialog==='register'&&<Dialog title="Register equity" eyebrow="STABLE INSTRUMENT IDENTITY" subtitle="Outside collector coverage is supported. Registration does not fetch prices." onClose={()=>{if(!saving)setDialog(null);}}><form id="register-form" onSubmit={e=>{e.preventDefault();const f=Object.fromEntries(new FormData(e.currentTarget));setSaving(true);setSaveError('');void api('/instruments',{id:f.id||crypto.randomUUID(),name:f.name,symbol:f.symbol,type:'EQUITY',validFrom:f.from}).then(async()=>{await loadInstruments();setDialog(null);setNotice('Equity registered. No market data was fetched.');}).catch(e=>setSaveError(errorMessage(e))).finally(()=>setSaving(false));}}><div className="dialog-body page-stack"><label className="field"><span>Existing stable ID, or blank for new</span><input name="id"/></label><label className="field"><span>Issuer name</span><input name="name" required maxLength={200}/></label><label className="field"><span>Display symbol</span><input name="symbol" required maxLength={50}/></label><label className="field"><span>Symbol valid from</span><input name="from" type="date" defaultValue={jakartaToday()} required/></label>{saveError&&<Notice kind="error">{saveError}</Notice>}</div><div className="dialog-footer"><button type="button" className="button ghost" disabled={saving} onClick={()=>setDialog(null)}>Cancel</button><button className="button primary" disabled={saving}>Register equity</button></div></form></Dialog>}
 {dialog&&typeof dialog==='object'&&<Dialog title={`${dialog.market.displaySymbol} · market data`} eyebrow="HOLDING CONTEXT" onClose={()=>setDialog(null)}><div className="dialog-body page-stack"><Badge kind={dialog.valuation.availability==='UNAVAILABLE'?'unknown':'info'}>{valuationLabel(dialog)}</Badge><p>Stable ID: {dialog.position.instrumentId}</p><p>Invested cost Rp {money(dialog.position.investedCost)} · Realized P/L Rp {money(dialog.position.realizedPnl)}</p><p>Price {money(dialog.valuation.price)} · Date {dialog.valuation.date??'UNKNOWN'} · Age {dialog.valuation.priceAgeDays??'UNKNOWN'} calendar days</p><p>Source {dialog.market.source??'UNKNOWN'} · {dialog.market.priceBasis} · revision {dialog.market.revision??'UNKNOWN'}</p><p>Retrieved {dialog.market.retrievedAt?recorded(dialog.market.retrievedAt):'UNKNOWN'} · Known {dialog.market.knownAt?recorded(dialog.market.knownAt):'UNKNOWN'}</p><p>Completeness {dialog.market.completeness}</p><details><summary>Feature readiness</summary>{Object.entries(dialog.market.features).map(([name,state])=><p key={name}>{name}: {state.availability} · {state.unavailableReason}</p>)}</details><Notice>Market-data quality is separate from reconciliation, P/L and mandate.</Notice></div><div className="dialog-footer"><StockLink id={dialog.position.instrumentId} onNavigate={next=>{setDialog(null);openStock(next);}}>Open Stock Detail</StockLink><button className="button" onClick={()=>setDialog(null)}>Done</button></div></Dialog>}
 </>;
}
createRoot(document.getElementById('root')!).render(<App/>);
