import assert from 'node:assert/strict';
import { test } from 'node:test';
import { renderToStaticMarkup as render } from 'react-dom/server';
import { ApiError, type Request } from './api.js';
import { OutcomeView, OutcomeDetails } from './OutcomePanel.js';
import { horizons, horizonCounts, OutcomeSession, type OutcomeCell, type Outcomes, type OutcomeState } from './outcomes.js';
import type { DecisionRun } from './decisions.js';
const id='10000000-0000-4000-8000-000000000001',rid='20000000-0000-4000-8000-000000000001';
const run={header:{runId:rid,capturedAt:'2026-10-03T04:13:45Z',targetSession:'2026-10-02'},rows:[{instrumentId:id,symbol:'SYN',configured:false,held:true}]} as DecisionRun;
const cell=(n:typeof horizons[number]=1):OutcomeCell=>({instrumentId:id,horizonSessions:n,resolution:'UNRESOLVED',materialized:false,newlyMaterialized:false,state:'PENDING',reason:'HORIZON_NOT_REACHED',anchorMarketDate:'2026-10-02',anchorClose:100,horizonMarketDate:null,horizonClose:null,priceReturnPct:null,outcomeKnownAt:null,recordedAt:null});
const response=(cells=horizons.map(n=>cell(n))):Outcomes=>({runId:rid,horizonSessions:null,outcomePolicyId:'outcome-v0.1.0',schemaVersion:1,assessedAt:'2026-10-10T10:00:00Z',newlyMaterializedCount:0,summary:{cells:cells.length,available:0,terminalUnavailable:0,unresolved:cells.length,materialized:0,newlyMaterialized:0},cells});
const state=(result:Outcomes|null):OutcomeState=>({result,busy:false,evaluating:null,error:'',message:'',lastEvaluationAt:null});
const view=(s:OutcomeState,r=run)=>render(<OutcomeView run={r} state={s} onEvaluate={()=>{}} onRead={()=>{}}/>);
test('no captured rows and initial loading do not fabricate cells or write automatically',()=>{assert.match(view(state(response([])),{...run,rows:[]}),/No captured instruments/);assert.match(view({...state(null),busy:true}),/Loading outcome assessments/);assert.doesNotMatch(view(state(null)),/0\.00%/);});
test('full captured population and all four unresolved horizons remain neutral and retryable',()=>{const html=view(state(response()));assert.equal((html.match(/data-outcome-horizon=/g)??[]).length,4);assert.equal((html.match(/<strong class="outcome-state">UNRESOLVED/g)??[]).length,4);assert.match(html,/Outside configured scope · Held at capture/);assert.match(html,/HORIZON_NOT_REACHED/);assert.match(html,/No terminal outcomes recorded/);assert.doesNotMatch(html,/role="alert"|0\.00%|win rate/i);});
for(const value of [10,0,-10])test('AVAILABLE price return '+value+' keeps zero and sign with existing display formatting',()=>{const c={...cell(),resolution:'TERMINAL' as const,state:'AVAILABLE',reason:null,horizonMarketDate:'2026-10-05',horizonClose:100+value,priceReturnPct:value,materialized:true,outcomeKnownAt:'2026-10-10T10:00:00Z',recordedAt:'2026-10-10T10:00:01Z'};const html=view(state(response([c])));assert.match(html,new RegExp('Price return '+value.toFixed(2)+'%'));assert.match(html,/2026-10-05/);assert.match(html,/Committed/);assert.doesNotMatch(html,/role="alert"/);});
for(const terminal of ['ANCHOR_UNAVAILABLE','DATA_UNAVAILABLE','BASIS_UNCERTAIN'])test('terminal '+terminal+' is factual, distinct and never missing-as-zero',()=>{const html=view(state(response([{...cell(),resolution:'TERMINAL',state:terminal,reason:'FACTUAL_REASON',materialized:true}])));assert.match(html,new RegExp(terminal));assert.match(html,/FACTUAL_REASON/);assert.doesNotMatch(html,/role="alert"|Price return 0\.00%/);});
test('mixed summary uses factual API cells only; previews have no committed clocks',()=>{const cells=[cell(),{...cell(),instrumentId:'other',state:'AVAILABLE',resolution:'TERMINAL' as const,priceReturnPct:0},{...cell(),instrumentId:'third',state:'DATA_UNAVAILABLE',resolution:'TERMINAL' as const}];assert.deepEqual(horizonCounts(cells,1),{total:3,unresolved:1,terminal:2,available:1,terminalUnavailable:1});const html=view(state(response(cells)));assert.match(html,/Preview · not recorded/);assert.doesNotMatch(html,/average return|win rate|alpha|expectancy/i);});
test('detail separates capture, read cutoff and late committed clocks; null return is unavailable',()=>{const c={...cell(),state:'AVAILABLE',resolution:'TERMINAL' as const,materialized:true,outcomeKnownAt:'2026-10-15T10:00:00Z',recordedAt:'2026-10-15T10:00:01Z'};const html=render(<OutcomeDetails cell={c} policy="outcome-v0.1.0" assessedAt="2026-10-16T10:00:00Z" capturedAt={run.header.capturedAt} targetSession="2026-10-02"/>);for(const token of ['2026-10-03','2026-10-15','2026-10-16','Outcome recorded at','Anchor close','Price return','Unavailable','cash dividends'])assert.ok(html.includes(token),token);assert.doesNotMatch(html,/data\/raw|originatingXid/);assert.match(view(state(response([c]))),/Price return Unavailable/);});
function harness(timeout=65000){let latest=state(null);const calls:{path:string;body:unknown;signal?:AbortSignal;resolve:(v:Outcomes)=>void;reject:(e:unknown)=>void}[]=[];const request:Request=<T,>(path:string,body?:unknown,signal?:AbortSignal)=>new Promise<T>((resolve,reject)=>calls.push({path,body,signal,resolve:v=>resolve(v as T),reject}));return {session:new OutcomeSession(s=>{latest=s;},request,timeout),calls,state:()=>latest};}
async function loaded(){const h=harness();const p=h.session.read(rid);assert.equal(h.calls[0].body,undefined);h.calls[0].resolve(response());await p;return h;}
for(const created of [0,1])test('explicit evaluation '+created+' materializations is success and refreshes read without changing capture',async()=>{const h=await loaded(),before=JSON.stringify(run);const p=h.session.evaluate(rid,1);assert.deepEqual(h.calls[1].body,{horizonSessions:1});assert.equal(h.state().evaluating,1);h.calls[1].resolve({...response(),newlyMaterializedCount:created,summary:{...response().summary,newlyMaterialized:created}});await Promise.resolve();assert.equal(h.calls[2].body,undefined);h.calls[2].resolve(response());await p;assert.equal(h.state().error,'');assert.match(h.state().message,created?/1 new terminal/:/No outcomes resolved/);assert.equal(JSON.stringify(run),before);});
test('duplicate and concurrent horizon clicks are ignored while busy',async()=>{const h=await loaded();const p=h.session.evaluate(rid,1);await h.session.evaluate(rid,1);await h.session.evaluate(rid,5);assert.equal(h.calls.length,2);assert.match(view(h.state()),/disabled=""/);h.calls[1].resolve(response());await Promise.resolve();h.calls[2].resolve(response());await p;});
test('route change aborts stale evaluation and its completion cannot refresh the new run',async()=>{const h=await loaded();const old=h.session.evaluate(rid,1);const next=h.session.read(id);assert.equal(h.calls[1].signal?.aborted,true);h.calls[2].resolve({...response(),runId:id});await next;h.calls[1].resolve(response());await old;assert.equal(h.state().result?.runId,id);assert.equal(h.calls.length,3);});
test('errors, missing run and successful evaluation with failed refresh remain separate',async()=>{const h=await loaded();let p=h.session.evaluate(rid,1);h.calls[1].reject(new ApiError('503',503));await p;assert.match(h.state().error,/service unavailable/);assert.equal(h.state().result?.cells.length,4);p=h.session.evaluate(rid,5);h.calls[2].resolve({...response(),newlyMaterializedCount:1});await Promise.resolve();h.calls[3].reject(new Error('offline'));await p;assert.match(h.state().error,/Evaluation completed/);assert.match(h.state().message,/1 new terminal/);p=h.session.read(id);h.calls[4].reject(new ApiError('404',404));await p;assert.equal(h.state().error,'Decision capture not found.');});
test('invalid route makes no request; timeout ends busy state without inventing results',async()=>{const h=harness(1);await h.session.read('bad');assert.equal(h.calls.length,0);const p=h.session.read(rid);await new Promise(resolve=>setTimeout(resolve,5));h.calls[0].reject(new Error('abort'));await p;assert.equal(h.state().busy,false);assert.match(h.state().error,/timed out/);assert.equal(h.state().result,null);});

test('zero new records preserves existing terminal outcomes without claiming none resolved',async()=>{const h=await loaded(),terminal={...cell(),state:'AVAILABLE',resolution:'TERMINAL' as const,materialized:true,priceReturnPct:0};const r={...response([terminal]),summary:{...response([terminal]).summary,unresolved:0,materialized:1,available:1}};const p=h.session.evaluate(rid,1);h.calls[1].resolve(r);await Promise.resolve();h.calls[2].resolve(r);await p;assert.match(h.state().message,/Existing terminal outcomes are retained/);assert.doesNotMatch(h.state().message,/No outcomes resolved/);assert.equal(h.state().result?.cells[0].priceReturnPct,0);});
