import { useEffect, useRef, useState } from 'react';
import { api, errorMessage } from './api';
import { readSnapshotFile, type SnapshotPreview } from './snapshotCsv';
import { readDraft, saveDraft, clearDraft, type DraftHolding } from './reconciliationDraft';
import { MissingInstruments } from './MissingInstruments';
import { cutoffIso, difference, quantity, type ExpectedHolding, type Reconciliation } from './view';
import { Empty, Icon, LoadingSkeleton, Metric, Notice, PageHeader, StatusBadge, InstrumentCell } from './ui';
export function ReconciliationPanel({portfolioId,through,cutoff,contextDirty,onRegistryChanged}: {portfolioId: string; through: string; cutoff: string; contextDirty: boolean; onRegistryChanged:()=>Promise<void>}) {
 const [restored]=useState(()=>readDraft(portfolioId));const [cash,setCash]=useState(restored?.expectedCash??'');const [holdings,setHoldings]=useState<DraftHolding[]>(restored?.holdings??[]);const [draftError,setDraftError]=useState('');const [registering,setRegistering]=useState(false);
 useEffect(()=>{setDraftError(saveDraft({version:1,portfolioId,expectedCash:cash,holdings,through,cutoff}));},[portfolioId,cash,holdings,through,cutoff]);
const [result,setResult]=useState<Reconciliation|null>(null);const [error,setError]=useState('');const [busy,setBusy]=useState(false);const [filter,setFilter]=useState('all');const [editor,setEditor]=useState(true);const pending=useRef<AbortController|null>(null);
 const [snapshot,setSnapshot]=useState<SnapshotPreview|null>(null);const [snapshotError,setSnapshotError]=useState('');const [reading,setReading]=useState(false);const fileGeneration=useRef(0);const fileInput=useRef<HTMLInputElement>(null);
 const invalidate=()=>{pending.current?.abort();pending.current=null;setBusy(false);setResult(null);setError('');};
 useEffect(()=>{invalidate();fileGeneration.current++;setSnapshot(null);setSnapshotError('');setReading(false);return ()=>{pending.current?.abort();fileGeneration.current++;};},[portfolioId,through,cutoff,contextDirty]);
 function edit(index: number,field: keyof ExpectedHolding,value: string) {invalidate();setHoldings(rows=>rows.map((row,i)=>i===index?{...row,[field]:value,...(field==='symbol'||field==='instrumentId'?{accounts:undefined,mandates:undefined}:{})}:row));}
 async function loadSnapshot(file?: File) {
  invalidate();const generation=++fileGeneration.current;setSnapshot(null);setSnapshotError('');setReading(!!file);
  if(!file)return;
  try {const next=await readSnapshotFile(file);if(generation===fileGeneration.current){setSnapshot(next);setEditor(true);}}
  catch(e){if(generation===fileGeneration.current){setSnapshotError(errorMessage(e));setEditor(true);}}
  finally {if(generation===fileGeneration.current)setReading(false);}
 }
 function cancelSnapshot(){fileGeneration.current++;setSnapshot(null);setSnapshotError('');setReading(false);if(fileInput.current)fileInput.current.value='';}
 async function compare() {if(contextDirty||busy||reading||snapshot||registering)return;const controller=new AbortController();pending.current?.abort();pending.current=controller;setBusy(true);setError('');setResult(null);try {const next=await api<Reconciliation>(`/portfolios/${portfolioId}/reconciliation/preview`,{through,cutoff:cutoffIso(cutoff),expectedCash:cash,holdings:holdings.map(h=>({instrumentId:h.instrumentId||null,symbol:h.symbol,shares:h.shares,averageCost:h.averageCost||null}))},controller.signal);if(!controller.signal.aborted){setResult(next);setFilter('all');setEditor(false);}}catch(e){if(!controller.signal.aborted)setError(errorMessage(e));}finally{if(!controller.signal.aborted)setBusy(false);}}
 const shown=result?.rows.filter(r=>filter==='all'||r.status!=='MATCH')??[];
 return <><PageHeader eyebrow="PORTFOLIO OPERATIONS" title="Portfolio reconciliation" subtitle="Compare your broker snapshot with the ledger at the selected date and knowledge cutoff."><span className="readonly-label"><Icon name="shield"/>Read-only comparison</span></PageHeader>
 <form className="panel" id="snapshot-form" onSubmit={e=>{e.preventDefault();void compare();}}><div className="panel-head"><div className="panel-title"><span className="step-number">01</span><h2>Broker snapshot</h2></div><div className="record-actions snapshot-actions"><button type="button" className="button" disabled={registering} onClick={()=>fileInput.current?.click()}><Icon name="upload"/>Upload Snapshot CSV</button><input ref={fileInput} id="snapshot-file" className="sr-only" tabIndex={-1} type="file" accept=".csv,text/csv" aria-label="Upload Snapshot CSV" onClick={e=>{e.currentTarget.value='';}} disabled={registering} onChange={e=>void loadSnapshot(e.target.files?.[0])}/><button type="button" className="text-button" aria-expanded={editor} aria-controls="snapshot-editor" onClick={()=>setEditor(!editor)}>{editor?'Hide inputs':'Edit snapshot'} <Icon name="chevron"/></button><button type="button" className="text-button" disabled={registering} onClick={()=>{const message=clearDraft(portfolioId);if(message){setDraftError(message);return;}invalidate();cancelSnapshot();setHoldings([]);setCash('');setEditor(true);}}>Clear Draft</button></div></div><div id="snapshot-editor" hidden={!editor} className="reconcile-editor"><div className="fields"><label className="field"><span>As-of / through date</span><input value={through} readOnly aria-describedby="reconcile-dates"/></label><label className="field"><span>Knowledge cutoff · WIB</span><input value={cutoff?cutoff.replace('T',' '):'Now · WIB'} readOnly/></label><label className="field"><span>Expected cash · IDR</span><input name="expectedCash" type="number" step="any" min="-1000000000000" max="1000000000000" required value={cash} onChange={e=>{invalidate();setCash(e.target.value);}}/></label></div><p id="reconcile-dates" className="muted input-unit">Change through/cutoff in the portfolio context above. Quantities are SHARES.</p>
 {draftError&&<Notice kind="error">{draftError}</Notice>}
 {reading&&<Notice>Reading snapshot locally…</Notice>}{snapshotError&&<Notice kind="error">{snapshotError}</Notice>}
 {snapshot&&<section className="page-stack snapshot-preview" aria-label="Snapshot CSV preview"><h3>Snapshot CSV preview</h3><p role="status">{snapshot.rowsRead} rows read · {snapshot.validRows} valid · {snapshot.holdings.length} holdings · {snapshot.sourceAccounts} source accounts · {snapshot.errors.length} errors</p>{snapshot.duplicateGroups>0&&<Notice>{snapshot.duplicateGroups} duplicate-symbol groups consolidated. All contributing rows are listed below.</Notice>}<p className="muted">Local preview only. Source accounts and mandates are informational. Apply replaces expected holdings; cash stays unchanged. Compare Portfolio checks registered instrument identities.</p>{snapshot.errors.length>0&&<Notice kind="error"><ul>{snapshot.errors.map((message,i)=><li key={i}>{message}</li>)}</ul></Notice>}<div className="table-scroll" tabIndex={0} aria-label="Snapshot CSV holdings preview"><table><thead><tr><th>Symbol</th><th className="num">Shares</th><th className="num">Average cost · IDR</th><th>CSV rows</th><th>Source accounts</th><th>Mandates · informational</th></tr></thead><tbody>{snapshot.holdings.map(h=><tr key={h.symbol}><td>{h.symbol}</td><td className="num">{h.shares}</td><td className="num">{h.averageCost??'Unknown'}</td><td>{h.rows.join(', ')}</td><td>{h.accounts.join(', ')||'—'}</td><td>{h.mandates.join(', ')||'—'}</td></tr>)}</tbody></table></div><div className="record-actions"><button type="button" className="button ghost" onClick={cancelSnapshot}>Cancel</button><button type="button" className="button primary" disabled={snapshot.errors.length>0||registering} onClick={()=>{invalidate();setHoldings(snapshot.holdings.map(({instrumentId,symbol,shares,averageCost,accounts,mandates})=>({instrumentId,symbol,shares,averageCost,accounts,mandates})));setEditor(true);cancelSnapshot();}}>Apply Snapshot</button></div></section>}
 <MissingInstruments holdings={snapshot?.errors.length===0?snapshot.holdings:holdings} through={through} onInvalidate={invalidate} onRegistryChanged={onRegistryChanged} onBusy={setRegistering}/>
 <fieldset disabled={registering} className="snapshot-inputs"><details className="snapshot-holdings" open><summary><Icon name="layers"/>{holdings.length} expected holdings</summary><div className="table-scroll" tabIndex={0} aria-label="Expected holdings input"><table className="expected-table"><thead><tr><th>Symbol</th><th>Stable ID (optional)</th><th className="num">Shares</th><th className="num">Average cost · IDR</th><th><span className="sr-only">Remove</span></th></tr></thead><tbody>{holdings.map((h,i)=><tr key={i}><td><input aria-label={`Holding ${i+1} symbol`} maxLength={50} value={h.symbol} onChange={e=>edit(i,'symbol',e.target.value)} placeholder="e.g. ANTM"/></td><td><input aria-label={`Holding ${i+1} stable ID`} value={h.instrumentId??''} onChange={e=>edit(i,'instrumentId',e.target.value)} placeholder="UUID"/></td><td><input aria-label={`Holding ${i+1} shares`} type="number" min="1" max="1000000000" step="1" required value={h.shares} onChange={e=>edit(i,'shares',e.target.value)}/></td><td><input aria-label={`Holding ${i+1} average cost`} type="number" min="0" max="1000000000000" step="any" value={h.averageCost??''} onChange={e=>edit(i,'averageCost',e.target.value)} placeholder="Unknown"/></td><td><button type="button" className="icon-button" aria-label={`Remove holding ${i+1}`} onClick={()=>{invalidate();setHoldings(rows=>rows.filter((_,n)=>n!==i));}}><Icon name="close"/></button></td></tr>)}</tbody></table></div><button type="button" className="text-button add-row" disabled={holdings.length>=200} onClick={()=>{invalidate();setHoldings(rows=>[...rows,{instrumentId:null,symbol:'',shares:'',averageCost:''}]);}}><Icon name="plus"/>Add holding</button></details></fieldset></div>
 <div className="panel-footer"><p><Icon name="lock"/>Comparison creates no events or corrections.</p><button className="button primary" disabled={busy||contextDirty||reading||!!snapshot||registering}>Compare Portfolio <Icon name="arrow"/></button></div></form>
 <div className="section-heading"><div className="panel-title"><span className="step-number">02</span><h2>Comparison results</h2></div><span className="muted">Ledger − broker snapshot</span></div><div aria-live="polite">{contextDirty?<Empty title="Context changed">Apply the through date and knowledge cutoff above before comparing.</Empty>:busy?<LoadingSkeleton/>:error?<Notice kind="error">{error} Your ledger has not changed.</Notice>:!result?<Empty title="Ready to compare">Enter the expected cash and holdings. Changing inputs clears previous results.</Empty>:<>
 <Notice kind={result.status==='MATCH'?'info':'review'}><strong>{result.status==='MATCH'?'Your snapshot matches the ledger':'Differences need your review'}</strong> · {result.review} holding differences · {result.cashDifference===0?'Cash matches':'Cash differs'} <StatusBadge status={result.status}/></Notice>
 <div className="summary-strip results-panel"><Metric label="Ledger cash" value={quantity(result.ledgerCash)} note="IDR · reconstructed balance"/><Metric label="Expected cash" value={quantity(result.expectedCash)} note="IDR · broker snapshot"/><Metric label="Cash difference" value={difference(result.cashDifference)} note="Ledger − expected" tone={result.cashDifference?'warn':''}/><Metric label="Matched holdings" value={result.matched} note={`${result.ledgerHoldings} ledger / ${result.expectedHoldings} expected`}/><Metric label="Require review" value={result.review} note={`${result.unknown} unknown instruments`} tone={result.review?'warn':''}/><Metric label="Missing holdings" value={result.missing} note="Across either source"/></div>
 <div className="panel results-panel"><div className="table-toolbar"><div className="tabs" aria-label="Comparison filters">{['all','review'].map(f=><button type="button" className={`tab ${filter===f?'active':''}`} aria-pressed={filter===f} key={f} onClick={()=>setFilter(f)}>{f==='all'?'All holdings':'Needs review'} <span className="tab-count">{f==='all'?result.rows.length:result.review}</span></button>)}</div><span className="table-note">No market prices in this comparison</span></div><div className="table-scroll" tabIndex={0} aria-label="Holding comparisons; scroll horizontally"><table className="reconcile-table"><caption className="sr-only">Ledger and expected holdings; unavailable values are not zero</caption><thead><tr><th rowSpan={2}>Holding</th><th colSpan={3} className="num">SHARES</th><th colSpan={3} className="num group-separator">AVERAGE COST · IDR</th><th rowSpan={2}>Status</th></tr><tr>{['Ledger','Expected','Difference','Ledger','Expected','Difference'].map((c,i)=><th key={i} className={`num ${i===3?'group-separator':''}`}>{c}</th>)}</tr></thead><tbody>{shown.map((r,i)=><tr key={r.instrumentId??r.symbol+i} className={r.status==='REVIEW'?'review-row':''}><td><InstrumentCell symbol={r.symbol}/></td>{[r.ledgerShares,r.expectedShares,r.shareDifference,r.ledgerAverageCost,r.expectedAverageCost,r.averageCostDifference].map((v,n)=><td key={n} className={`num ${n===3?'group-separator':''} ${n===2||n===5?v?'difference mismatch':'difference':''}`}>{n===2||n===5?difference(v):quantity(v)}</td>)}<td><StatusBadge status={r.status}/></td></tr>)}{!shown.length&&<tr><td colSpan={8}>No holdings require review.</td></tr>}</tbody></table></div><div className="table-bottom"><span>{shown.length} of {result.rows.length} holdings · — = unavailable in that source</span><span>Through {result.through}</span></div></div></>}</div></>;
}
