import assert from 'node:assert/strict';
import { test } from 'node:test';
import { renderToStaticMarkup } from 'react-dom/server';
import { ApiError, api, type Request } from './api.js';
import { Navigation } from './ui.js';
import { RowDetails, Screener, ScreenerResults } from './ScreenerPage.js';
import { defaultControls, initialState, loadScreener, number, ScreenerSession, setupLabel, type Context, type ScreenerResponse, type ScreenerRow, type ScreenerState } from './screener.js';

const context: Context={through:'2026-09-30',cutoff:''};
const provenance={priceBasis:'RAW_AS_TRADED',source:'synthetic',currency:'IDR',volumeUnit:'SHARES',volumeBasis:'RAW_AS_TRADED',marketSegment:'REGULAR',revision:1,knownAt:'2026-10-01T00:00:00Z',retrievedAt:'2026-09-30T12:00:00Z',contentHash:'a'.repeat(64),priceSequenceStart:'2026-08-24',emaSeedStart:'2026-08-24',atrSeedStart:'2026-08-24',consecutiveSessions:28,referenceSnapshotIds:['synthetic-reference'],canonicalQuality:'DEGRADED',currentEvidence:null};
const row: ScreenerRow={instrumentId:'stock-1',symbol:'SYNTHETIC',displayName:'Synthetic equity',configured:true,held:true,mandate:'FAST_SWING',discoveryRank:1,eligibility:'ELIGIBLE',eligibilityReasons:[],setup:'CONFIRMED',setupEvaluated:true,setupReasons:['BREAKOUT'],episode:{id:'synthetic-episode',startDate:'2026-09-30',confirmationDate:'2026-09-30',endDate:null,endReason:null,ageSessions:0,confirmedAgeSessions:0,triggerPrice:110,watchThreshold:98},marketDate:'2026-09-30',close:111,changePercent:0,ema20:90,ema50:null,trend:'UNKNOWN',priorHigh20:100,priorLow20:89,distanceToHighPercent:11,volume:100,volumeRatio20:1,dailyValueProxyIdr:11100,monetaryLiquidity20Idr:9000,atr14:1.23456789,atrPercent:1,rs20Pp:0,rs60Pp:null,stale:false,noTrade:false,tradingStatus:'NORMAL',dataQuality:'PARTIAL',dataReasons:['OPTIONAL_FEATURES_UNAVAILABLE'],fieldStates:{ema50:{availability:'WARMUP',reason:'INSUFFICIENT_HISTORY'},rs60Pp:{availability:'WARMUP',reason:'RS_HISTORY_MISSING'}},provenance};
function fixture(): ScreenerResponse {return {policyId:'SCREENER_V0_1',through:context.through,targetSession:context.through,cutoff:'2026-10-01T12:00:00+00:00',historyAnchor:'2026-08-24',universe:'PILOT',universeSnapshotId:'synthetic-universe',replayScope:'FIXED_PILOT_KNOWN_INPUTS',inputHash:'a'.repeat(64),status:'PARTIAL',reasons:['OPTIONAL_FEATURES_UNAVAILABLE'],summary:{configured:1,eligible:1,ineligible:0,dataBlocked:0,evaluated:1,candidates:1,confirmed:1,watch:0,shortlisted:1,omittedConfirmed:0,omittedWatch:0,insufficientHistory:1,stale:0,unsupported:0,held:1,heldOutsideUniverse:0},marketContext:{instrumentId:'index',marketDate:context.through,trend:'UNKNOWN',volatility:'UNKNOWN',close:100,ema20:100,ema50:null,atr14:0,atrPercent:0,reasons:['EMA_HISTORY_MISSING'],fieldStates:{ema50:{availability:'WARMUP',reason:'INSUFFICIENT_HISTORY'}},provenance},page:{...defaultControls,total:1},discoveryIds:[row.instrumentId],heldIds:[row.instrumentId],rows:[structuredClone(row)]};}
const render=(result=fixture(),portfolioSelected=true,busy=false)=>renderToStaticMarkup(<ScreenerResults result={result} portfolioSelected={portfolioSelected} busy={busy} onOpen={()=>{}}/>);
function harness() {
 const calls:{path:string;signal?:AbortSignal;resolve:(result:ScreenerResponse)=>void;reject:(error:unknown)=>void}[]=[];
 let state: ScreenerState=initialState;
 const request: Request=<T,>(path:string,body?:unknown,signal?:AbortSignal)=>{assert.equal(body,undefined);return new Promise<T>((resolve,reject)=>calls.push({path,signal,resolve:result=>resolve(result as T),reject}));};
 const session=new ScreenerSession(next=>{state=next;},request);
 const query=(index=calls.length-1)=>new URL(calls[index].path,'http://test').searchParams;
 const first=async()=>{const pending=session.load(context,{...defaultControls});calls.at(-1)!.resolve(fixture());await pending;};
 return {calls,session,query,first,state:()=>state};
}
test('one enabled Screener navigation entry follows shell conventions',()=>{const html=renderToStaticMarkup(<Navigation page="screener" onNavigate={()=>{}}/>);assert.equal((html.match(/title="Screener"/g)??[]).length,1);assert.match(html,/aria-current="page" title="Screener"/);assert.doesNotMatch(html,/Screener · reserved/);});
test('COMPLETE renders a neutral status and exact backend summary',()=>{const r=fixture();r.status='COMPLETE';r.reasons=[];const html=render(r);assert.match(html,/Evaluation complete/);assert.match(html,/Configured/);assert.match(html,/Candidates/);assert.match(html,/Target session 2026-09-30/);assert.match(html,/Known by/);});
test('PARTIAL retains an evaluable confirmed setup and persistent coverage reason',()=>{const html=render();assert.match(html,/Coverage is partial/);assert.match(html,/OPTIONAL_FEATURES_UNAVAILABLE/);assert.match(html,/CONFIRMED/);});
test('BLOCKED states the evidence problem and unknown counts stay unavailable',()=>{const r=fixture();r.status='BLOCKED';r.summary.configured=null;r.summary.candidates=null;r.discoveryIds=[];const html=render(r);assert.match(html,/Screening could not be fully evaluated/);assert.match(html,/Unavailable/);assert.doesNotMatch(html,/No candidates met/);});
test('COMPLETE zero candidates is a factual non-error empty state',()=>{const r=fixture();r.status='COMPLETE';r.summary.candidates=0;r.discoveryIds=[];const html=render(r);assert.match(html,/No candidates met this descriptive setup/);assert.doesNotMatch(html,/role="alert"/);});
test('default request is read-only PILOT shortlist, limit20, with no initial pin or now cutoff',async()=>{const h=harness();await h.first();assert.equal(h.query().get('view'),'shortlist');assert.equal(h.query().get('limit'),'20');assert.equal(h.query().get('universe'),'PILOT');assert.equal(h.query().has('inputHash'),false);assert.equal(h.query().has('cutoff'),false);});
for(const [name,changes,key,value] of [['all view',{view:'all'},'view','all'],['setup filter',{setup:'WATCH'},'setup','WATCH'],['eligibility filter',{eligibility:'DATA_BLOCKED'},'eligibility','DATA_BLOCKED']] as const) {
 test(`${name} requests preserve resolved cutoff/hash`,async()=>{const h=harness();await h.first();const pending=h.session.load(context,{...defaultControls,...changes,offset:0});assert.equal(h.query().get(key),value);assert.equal(h.query().get('cutoff'),fixture().cutoff);assert.equal(h.query().get('inputHash'),fixture().inputHash);assert.equal(h.query().get('offset'),'0');h.calls.at(-1)!.resolve(fixture());await pending;});
}
test('page requests preserve through/filter/view and resolved pin',async()=>{const h=harness();await h.first();const pending=h.session.load(context,{...defaultControls,view:'all',setup:'NONE',eligibility:'ELIGIBLE',offset:20});assert.deepEqual(['through','cutoff','inputHash','view','setup','eligibility','offset'].map(key=>h.query().get(key)),[context.through,fixture().cutoff,fixture().inputHash,'all','NONE','ELIGIBLE','20']);h.calls.at(-1)!.resolve(fixture());await pending;});
for(const [name,next] of [['through',{...context,through:'2026-09-29'}],['cutoff',{...context,cutoff:'2026-10-01T09:00:00'}],['portfolio',{...context,portfolioId:'synthetic-portfolio'}]] as const) {
 test(`${name} change clears results and hash before a new response`,async()=>{const h=harness();await h.first();const pending=h.session.load(next,defaultControls);assert.equal(h.state().result,null);assert.equal(h.query().has('inputHash'),false);if(name==='cutoff')assert.equal(h.query().get('cutoff'),'2026-10-01T02:00:00.000Z');if(name==='portfolio')assert.equal(h.query().get('portfolioId'),'synthetic-portfolio');h.calls.at(-1)!.resolve(fixture());await pending;});
}
test('editing context aborts immediately, clears rows, and ignores a late result',async()=>{const h=harness();const pending=h.session.load(context,defaultControls);h.session.invalidate();assert.equal(h.calls[0].signal?.aborted,true);assert.deepEqual(h.state(),initialState);h.calls[0].resolve(fixture());await pending;assert.equal(h.state().result,null);});
test('409 INPUT_CHANGED clears rows, requires explicit refresh, and refresh resets pin',async()=>{const h=harness();await h.first();const pending=h.session.load(context,{...defaultControls,view:'all'});h.calls.at(-1)!.reject(new ApiError('INPUT_CHANGED',409,'INPUT_CHANGED'));await pending;assert.equal(h.state().refreshRequired,true);assert.equal(h.state().result,null);assert.match(h.state().error,/Underlying Screener inputs changed. Refresh the evaluation/);const count=h.calls.length;await h.session.load(context,defaultControls);assert.equal(h.calls.length,count);const refreshed=h.session.load(context,{...defaultControls,offset:0},true);assert.equal(h.query().has('inputHash'),false);assert.equal(h.query().has('cutoff'),false);assert.equal(h.query().get('offset'),'0');h.calls.at(-1)!.resolve({...fixture(),inputHash:'b'.repeat(64)});await refreshed;assert.equal(h.state().result?.inputHash,'b'.repeat(64));assert.equal(h.state().refreshRequired,false);});
test('page exposes a named refresh action and labeled context/filter inputs',()=>{const html=renderToStaticMarkup(<Screener portfolioId="" onOpenPortfolio={()=>{}}/>);assert.match(html,/Refresh evaluation/);assert.match(html,/Known by · WIB/);assert.match(html,/Discovery only/);assert.match(html,/name="screenerSetup"/);});
test('late success and error from ignored cancellation cannot overwrite latest context',async()=>{const h=harness();const old=h.session.load(context,defaultControls);const newer=h.session.load({...context,through:'2026-09-29'},defaultControls);h.calls[1].resolve({...fixture(),through:'2026-09-29'});await newer;h.calls[0].resolve(fixture());await old;assert.equal(h.state().result?.through,'2026-09-29');const stale=h.session.load(context,defaultControls);const latest=h.session.load({...context,portfolioId:'new'},defaultControls);h.calls[3].resolve({...fixture(),inputHash:'c'.repeat(64)});await latest;h.calls[2].reject(new ApiError('secret SQL',503));await stale;assert.equal(h.state().error,'');assert.equal(h.state().result?.inputHash,'c'.repeat(64));});
test('held rows survive an empty filtered discovery and do not alter summary counts',()=>{const r=fixture();r.discoveryIds=[];r.page.setup='FAILED';const html=render(r);assert.match(html,/All Held Positions/);assert.match(html,/SYNTHETIC/);assert.equal(r.summary.held,1);assert.equal(r.summary.candidates,1);});
test('held section survives paging load with same logical row object',async()=>{const h=harness();await h.first();const result=h.state().result!;const pending=h.session.load(context,{...defaultControls,offset:20});assert.strictEqual(h.state().result,result);const html=render(result,true,true);assert.match(html,/Loading Screener discovery/);assert.match(html,/All Held Positions/);assert.match(html,/SYNTHETIC/);h.calls.at(-1)!.resolve(fixture());await pending;});
test('candidate and held render the one backend row without deduping away either section',()=>{const r=fixture();const html=render(r);assert.equal(r.rows.length,1);assert.equal((html.match(/data-instrument-id="stock-1"/g)??[]).length,2);assert.equal((html.match(/111\.00/g)??[]).length,2);});
test('discovery order follows IDs, not row array, rank, symbol or values',()=>{const r=fixture();r.rows.push({...row,instrumentId:'stock-2',symbol:'AAA',discoveryRank:2});r.discoveryIds=['stock-2','stock-1'];r.heldIds=[];const html=render(r,false);assert.ok(html.indexOf('data-instrument-id="stock-2"')<html.indexOf('data-instrument-id="stock-1"'));});
test('not evaluated never displays No setup; evaluated NONE is explicit',()=>{const r=fixture();r.rows[0]={...row,setup:'NONE',setupEvaluated:false,eligibility:'DATA_BLOCKED'};const html=render(r);assert.match(html,/Not evaluated/);assert.doesNotMatch(html,/No setup/);assert.equal(setupLabel({...row,setup:'NONE'}),'NONE / No setup');});
test('null numeric values render unavailable and true zero remains zero',()=>{assert.equal(number(null),'Unavailable');assert.equal(number(0),'0.00');assert.equal(number(0,0),'0');const html=render();assert.match(html,/>Unavailable<\/td>/);assert.match(html,/>0\.00<\/td>/);});
test('UNKNOWN market trend and volatility remain UNKNOWN',()=>{const html=render();assert.match(html,/Trend · UNKNOWN/);assert.match(html,/Volatility · UNKNOWN/);assert.doesNotMatch(html,/Trend · NEUTRAL|Volatility · NORMAL/);});
test('mandates render neutral factual values and missing mandate stays unassigned',()=>{for(const mandate of ['FAST_SWING','LONG_SWING','INVEST',null] as const){const r=fixture();r.rows[0].mandate=mandate;assert.ok(render(r).includes(mandate ?? 'Unassigned'));}});
test('screen and details introduce no recommendation/action labels',()=>{const html=render()+renderToStaticMarkup(<RowDetails row={row} onClose={()=>{}}/>);assert.doesNotMatch(html,/>\s*(BUY|SELL|HOLD|REDUCE|EXIT|Entry|Recommended)\s*</);});
test('details expose every episode, reason, seed, reference and selected revision',()=>{const selected={sessionDate:'2026-09-30',revision:2,knownAt:'2026-10-01T02:00:00Z',retrievedAt:null,contentHash:'b'.repeat(64),canonicalQuality:'REJECTED',source:'synthetic'};const html=renderToStaticMarkup(<RowDetails row={{...row,eligibilityReasons:['SYNTHETIC_REASON'],provenance:{...provenance,currentEvidence:selected}}} onClose={()=>{}}/>);for(const token of ['synthetic-episode','triggerPrice','watchThreshold','SYNTHETIC_REASON','BREAKOUT','priceSequenceStart','emaSeedStart','atrSeedStart','synthetic-reference','knownAt','retrievedAt','Selected current evidence','REJECTED','1.23456789'])assert.ok(html.includes(token),token);});
test('unavailable optional feature reasons and original stale dates are discoverable',()=>{const html=renderToStaticMarkup(<RowDetails row={row} onClose={()=>{}}/>);assert.match(html,/RS_HISTORY_MISSING/);assert.match(html,/WARMUP/);const r=fixture();r.rows[0].marketDate='2026-09-29';r.rows[0].stale=true;assert.match(render(r),/2026-09-29/);assert.match(render(r),/>Stale</);});
test('missing historical identity stays unavailable with stable ID only in details',()=>{const r=fixture();r.rows[0].symbol=null;r.rows[0].displayName=null;assert.match(render(r),/>Unavailable<\/span>/);assert.match(renderToStaticMarkup(<RowDetails row={r.rows[0]} onClose={()=>{}}/>),/stock-1/);});
test('canonical DEGRADED remains separate from usable evaluation quality',()=>{const r=fixture();r.rows[0].dataQuality='COMPLETE';const html=render(r);assert.match(html,/Canonical: DEGRADED/);assert.match(html,/>\s*COMPLETE<\/span>/);});
test('selected empty portfolio has factual empty held state; discovery only has no held section',()=>{const r=fixture();r.heldIds=[];r.summary.held=0;assert.match(render(r),/No positive held positions/);assert.doesNotMatch(render(r,false),/All Held Positions/);assert.match(render(r,false),/SYNTHETIC/);});
for(const [status,expected] of [[400,'Check the through date'],[404,'selected portfolio is unavailable'],[503,'Retry the evaluation']] as const)test(`HTTP${status} is a sanitized error, not empty success`,async()=>{const h=harness();const pending=h.session.load(context,defaultControls);h.calls[0].reject(new ApiError('secret SQL connection string',status));await pending;assert.equal(h.state().result,null);assert.match(h.state().error,new RegExp(expected));assert.doesNotMatch(h.state().error,/secret|SQL|connection/);});
test('API client preserves HTTP status and code for existing message callers',async()=>{const original=globalThis.fetch;globalThis.fetch=async()=>new Response(JSON.stringify({code:'INPUT_CHANGED'}),{status:409});try{await assert.rejects(api('/screener'),error=>error instanceof ApiError&&error.status===409&&error.code==='INPUT_CHANGED');}finally{globalThis.fetch=original;}});

test('COMPLETE zero candidates is explicit even when all-view still contains ineligible instruments',()=>{const r=fixture();r.status='COMPLETE';r.summary.candidates=0;r.page.view='all';r.rows[0].eligibility='INELIGIBLE';r.rows[0].setupEvaluated=false;const html=render(r);assert.match(html,/No candidates met this descriptive setup/);assert.match(html,/SYNTHETIC/);});
