import { InstrumentDecisions } from './DecisionHistoryPage.js';
import { useEffect, useState, type MouseEvent } from 'react';
import { api, errorMessage } from './api.js';
import { type Context, number, setupLabel } from './screener.js';
import { jakartaToday, recorded } from './view.js';
import { Badge, Empty, LoadingSkeleton, Metric, Notice, PageHeader } from './ui.js';
import { emptyStockState, selectedHolding, selectedStock, StockSession, stockRoute, type HistoryRow, type StockRegistry, type StockResult, type StockState } from './stocks.js';

export function StockLink({id,children,onNavigate}:{id:string;children:React.ReactNode;onNavigate?:(id:string)=>void}){
 return <a className="text-button stock-link" href={stockRoute(id)} onClick={(e:MouseEvent<HTMLAnchorElement>)=>{if(onNavigate&&!e.ctrlKey&&!e.metaKey&&!e.shiftKey&&!e.altKey&&e.button===0){e.preventDefault();onNavigate(id);}}}>{children}</a>;
}
export function Stocks({onNavigate}:{onNavigate:(id:string)=>void}){
 const [search,setSearch]=useState(''),[offset,setOffset]=useState(0),[rows,setRows]=useState<StockRegistry[]>([]),[busy,setBusy]=useState(true),[error,setError]=useState('');
 useEffect(()=>{const c=new AbortController();setRows([]);setBusy(true);setError('');
  void api<StockRegistry[]>(`/instruments?${new URLSearchParams({search,offset:String(offset),limit:'20'})}`,undefined,c.signal)
   .then(r=>{if(!c.signal.aborted)setRows(r);}).catch(e=>{if(!c.signal.aborted)setError(errorMessage(e));}).finally(()=>{if(!c.signal.aborted)setBusy(false);});return()=>c.abort();
 },[search,offset]);
 return <div className="page-stack stocks-page"><PageHeader eyebrow="LOCAL RESEARCH · READ ONLY" title="Stocks" subtitle="Locally retained instruments. Registry identity is not historical Screener evidence."/>
  <label className="field stocks-search"><span>Search symbol or name</span><input name="stockSearch" type="search" maxLength={200} value={search} onChange={e=>{setSearch(e.target.value);setOffset(0);}}/></label>
  <Notice>Current/effective registry metadata · UNKNOWN remains visible. This list includes locally known benchmark instruments; it does not discover FullIdx.</Notice>
  {error&&<Notice kind="error">{error}</Notice>}{busy?<LoadingSkeleton label="Loading local instruments…"/>:rows.length?<div className="panel table-scroll" tabIndex={0}><table className="stocks-table"><caption className="sr-only">Local instruments, ordered by effective display symbol then stable ID</caption><thead><tr>{['Symbol','Name','Local type','Market date','Close','Data state'].map(t=><th key={t} scope="col">{t}</th>)}</tr></thead><tbody>{rows.map(r=><tr key={r.id}><td><StockLink id={r.id} onNavigate={onNavigate}>{r.symbol}</StockLink>{!r.hasEffectiveSymbol&&<small className="amount-secondary">Effective symbol history unavailable · {r.symbolSource??'UNAVAILABLE'}</small>}</td><td>{r.name}</td><td><Badge kind={r.type==='UNKNOWN'?'unknown':'outline'}>{r.type}</Badge></td><td>{r.marketDate??'UNAVAILABLE'}</td><td className="num">{number(r.close)}</td><td>{r.close===null?'UNAVAILABLE':r.marketDate!<jakartaToday()?'STALE':'CURRENT'} · {r.quality}</td></tr>)}</tbody></table></div>:!error&&<Empty title="No local instruments match">Change the search. No provider lookup is performed.</Empty>}
  <div className="panel panel-body wrap" aria-label="Stocks pagination"><span>{offset+1} onward · 20 per page</span><button className="button" disabled={busy||offset===0} onClick={()=>setOffset(n=>Math.max(0,n-20))}>Previous</button><button className="button" disabled={busy||rows.length<20||offset>=10000} onClick={()=>setOffset(n=>n+20)}>Next</button></div>
 </div>;
}
export function PriceChart({rows}:{rows:Pick<HistoryRow,'date'|'close'>[]}){
 const usable=rows.filter(r=>r.close!==null);if(usable.length<2)return <p className="muted">Insufficient usable history for a price chart (need at least 2 observations).</p>;
 const values=usable.map(r=>r.close!),min=Math.min(...values),max=Math.max(...values),span=max-min||1;
 const first=Date.parse(rows[0].date),duration=Math.max(1,Date.parse(rows.at(-1)!.date)-first);
 const points=rows.map(r=>r.close===null?null:`${40+(Date.parse(r.date)-first)/duration*640},${170-(r.close-min)/span*140}`);
 const segments:string[]=[];let current:string[]=[];for(const p of points){if(p===null){if(current.length)segments.push(current.join(' '));current=[];}else current.push(p);}if(current.length)segments.push(current.join(' '));
 return <svg className="stock-chart" viewBox="0 0 720 210" role="img" aria-label="Retained close prices by market date; table below is authoritative"><title>Retained close price history</title><path d="M40 20V175H680" className="chart-axis"/>{segments.map((p,i)=><polyline key={i} points={p} className="chart-line"/>)}{points.map((p,i)=>{if(p===null)return null;const [x,y]=p.split(',');return <circle key={i} cx={x} cy={y} r="3" className="chart-point"/>;})}<text x="40" y="200">{rows[0].date}</text><text x="680" y="200" textAnchor="end">{rows.at(-1)!.date}</text><text x="45" y="28">{number(max)}</text><text x="45" y="168">{number(min)}</text></svg>;
}
export function StockResults({result,portfolioSelected}:{result:StockResult;portfolioSelected:boolean}){
 const h=result.history,identity=h.registry,latest=h.rows.at(-1),row=selectedStock(result),holding=selectedHolding(result);
 const index=result.screener?.marketContext.instrumentId===identity.id?result.screener.marketContext:null;
 const features=[['ema20','EMA20'],['ema50','EMA50'],['atr14','ATR14'],['atrPercent','ATR %'],['priorHigh20','Prior high 20'],['priorLow20','Prior low 20'],['volumeRatio20','Volume ratio 20'],['rs20Pp','RS20 · pp'],['rs60Pp','RS60 · pp']] as const;
 return <>
  <PageHeader eyebrow="STOCK DETAIL · READ ONLY" title={identity.symbol} subtitle={identity.name}/>
  <section className="panel panel-body page-stack" aria-label="Current registry metadata"><h2>Current registry metadata</h2><p>Stable instrument ID <span className="mono break-word">{identity.id}</span></p><p>Display symbol source {identity.symbolSource??'UNKNOWN'} · Type {identity.type} · Currency {identity.currency} · Registry display date {h.registryAsOf}</p><Notice>Registry metadata is not fully knowledge-dated. It does not establish historical classification, board/status or Screener eligibility.</Notice></section>
  <p className="read-context muted">Through {h.through} · Known by <time dateTime={h.cutoff} title={h.cutoff}>{recorded(h.cutoff)}</time><small className="amount-secondary">Exact UTC cutoff {h.cutoff}</small></p>
  <section className="panel panel-body" aria-label="Latest canonical observation"><h2>Latest canonical observation</h2>{latest?<><div className="summary-strip stocks-metrics">{(['open','high','low','close','volume'] as const).map(f=><Metric key={f} label={f.toUpperCase()} value={number(latest[f])} note="Retained observation"/>)}</div><p>Market date {latest.date} · {latest.date<h.through?'STALE · older than through':'CURRENT'} · {latest.evidence.canonicalQuality} · {latest.availability}</p>{latest.reason&&<Notice kind="review">{latest.reason}; selected revision is retained without fallback.</Notice>}</>:<Empty title="No visible canonical price">No market observation exists under this through/cutoff.</Empty>}</section>
  <section className="panel panel-body page-stack" aria-label="Retained price history"><h2>Retained price history</h2><p className="muted">Latest {h.limit} visible sessions · ascending market date · observed prices, not certified comparability. Unknown session gaps are not filled.</p><PriceChart rows={h.rows}/><div className="table-scroll" tabIndex={0}><table className="stock-history-table"><caption className="sr-only">Authoritative retained history; unavailable values are not zero</caption><thead><tr>{['Date','Open','High','Low','Close','Volume','Quality / Availability','Revision'].map(t=><th key={t} scope="col">{t}</th>)}</tr></thead><tbody>{h.rows.map(r=><tr key={r.date}><td>{r.date}</td>{(['open','high','low','close','volume'] as const).map(f=><td key={f} className="num">{number(r[f])}</td>)}<td>{r.evidence.canonicalQuality} · {r.availability}{r.reason&&<small>{r.reason}</small>}</td><td>{r.evidence.revisionNumber}</td></tr>)}</tbody></table></div></section>
  <section className="panel panel-body page-stack" aria-label="Technical context"><h2>Technical context</h2><p>Knowledge-dated evaluation evidence · trend {row?.trend??index?.trend??'UNKNOWN'}</p><div className="stock-features">{features.map(([f,label])=>{const value=row?.[f]??(index&&f in index?(index as unknown as Record<string,number|null>)[f]:null);const state=row?.fieldStates[f]??index?.fieldStates[f];return <div className="metric" key={f}><span>{label}</span><strong>{number(value??null)}</strong><Badge kind="unknown">{state?.availability??(value==null?'UNAVAILABLE':'AVAILABLE')}</Badge><small>{state?.reason??(value==null?'NOT_EVALUATED_BY_CURRENT_SCREENER':'')}</small></div>;})}</div></section>
  <section className="panel panel-body page-stack" aria-label="Stock Screener context"><h2>Screener context</h2><p>Market context · trend {result.screener?.marketContext.trend??'UNKNOWN'} · volatility {result.screener?.marketContext.volatility??'UNKNOWN'}</p>{row?<><p><Badge kind={row.eligibility==='DATA_BLOCKED'?'unknown':'outline'}>{row.eligibility}</Badge> · {setupLabel(row)} · setupEvaluated {String(row.setupEvaluated)}</p><p>{[...row.eligibilityReasons,...row.setupReasons].join(' · ')}</p><p>Distance to prior high {number(row.distanceToHighPercent)}% · Frozen trigger {number(row.episode?.triggerPrice??null)}</p>{row.episode&&<pre className="stock-json">{JSON.stringify(row.episode,null,2)}</pre>}</>:<p>{result.screenerError?`Screener evaluation unavailable: ${result.screenerError}`:result.screener?.universeSnapshotId===null?'Screener universe unavailable at selected cutoff.':'Not evaluated by current Screener universe'}</p>}</section>
  {portfolioSelected&&<section className="panel panel-body page-stack" aria-label="Stock portfolio context"><h2>Portfolio context</h2>{result.portfolioError?<Notice kind="review">Portfolio context unavailable: {result.portfolioError}</Notice>:holding?<><Badge>Held</Badge><div className="stock-features">{Object.entries({Shares:holding.position.shares,'Average cost':holding.position.averageCost,'Invested cost':holding.position.investedCost,'Market value':holding.valuation.marketValue,'Unrealized P/L':holding.valuation.unrealizedPnl}).map(([k,v])=><Metric key={k} label={k} value={number(v)} note="Same through/cutoff"/>)}</div><p>Mandate {holding.activeThesis?.mandate??'Unassigned'} · Active thesis version {holding.activeThesis?.version??'UNAVAILABLE'} · Thesis status {holding.activeThesis?(holding.activeThesis.active?'ACTIVE':'INACTIVE'):'UNASSIGNED'}</p></>:<p>Not held in selected portfolio</p>}</section>}
  {!portfolioSelected&&<p className="muted">No portfolio selected.</p>}
  <details className="panel panel-body" aria-label="Stock data and provenance"><summary>Data &amp; Provenance</summary><p>Identity/reference status: {(row?.provenance.referenceSnapshotIds??index?.provenance.referenceSnapshotIds??[]).length?'Retained knowledge-dated evidence':'UNKNOWN'}</p><p>Screener universe snapshot {result.screener?.universeSnapshotId??'UNKNOWN'}</p><p>Price basis certification {row?.provenance.priceBasis??index?.provenance.priceBasis??'UNKNOWN'}</p><p>Session confirmation: {latest?.evidence.sessionReference?'Retained session assertion; see knowledge boundary':'UNKNOWN'}</p><pre className="stock-json">{JSON.stringify({selectedCanonicalEvidence:latest?.evidence??null,knowledgeDatedEvaluation:row?.provenance??index?.provenance??null},null,2)}</pre></details>
 </>;
}
export function StockDetail({id,portfolioId,portfolioName,onOpenPortfolio,onOpenDecision}:{id:string;portfolioId:string;portfolioName?:string;onOpenPortfolio:()=>void;onOpenDecision?:(id:string)=>void}){
 const [context,setContext]=useState<Context>({through:jakartaToday(),cutoff:'',portfolioId:portfolioId||undefined}),[dirty,setDirty]=useState(false);
 const [state,setState]=useState<StockState>(emptyStockState),[session]=useState(()=>new StockSession(setState));
 useEffect(()=>{void session.load(id,context);return()=>session.invalidate();},[id,session]);
 function edit(next:Context){session.invalidate();setContext(next);setDirty(true);}
 return <div className="page-stack stock-detail-page"><form className="panel panel-body screener-context" aria-label="Stock context" onSubmit={e=>{e.preventDefault();setDirty(false);void session.load(id,context);}}><label className="field"><span>Through · market date</span><input name="stockThrough" type="date" required min="1900-01-01" max={jakartaToday()} value={context.through} onChange={e=>edit({...context,through:e.target.value})}/></label><label className="field"><span>Known by · WIB</span><input name="stockCutoff" type="datetime-local" step="1" value={context.cutoff} onChange={e=>edit({...context,cutoff:e.target.value})}/><small>Blank resolves now; all detail reads reuse the API's exact cutoff.</small></label><label className="field"><span>Portfolio · optional</span><select name="stockPortfolio" value={context.portfolioId??''} onChange={e=>edit({...context,portfolioId:e.target.value||undefined})}><option value="">Discovery only</option>{portfolioId&&<option value={portfolioId}>{portfolioName??portfolioId}</option>}</select><button type="button" className="text-button" onClick={onOpenPortfolio}>Open another portfolio</button></label><div className="wrap"><button className="button" type="submit">Apply context</button><button className="button ghost" type="button" onClick={()=>{const next={...context,cutoff:''};setContext(next);setDirty(false);void session.load(id,next);}}>Now</button></div></form>{dirty&&<Notice>Context changed. Apply to evaluate.</Notice>}{state.busy&&<LoadingSkeleton label="Loading stock detail…"/>}{state.error&&<Notice kind="error">{state.error}</Notice>}{state.result&&<StockResults result={state.result} portfolioSelected={!!context.portfolioId}/>}<InstrumentDecisions id={id} onNavigate={onOpenDecision}/></div>;
}
