import assert from 'node:assert/strict';
import { test } from 'node:test';
import { renderToStaticMarkup } from 'react-dom/server';
import { type Request, ApiError } from './api.js';
import { Navigation } from './ui.js';
import { PriceChart, StockLink, StockResults } from './StocksPage.js';
import { StockSession, emptyStockState, type StockHistory, type StockResult, type StockState } from './stocks.js';
import { type ScreenerResponse } from './screener.js';
const id='10000000-0000-4000-8000-000000000001';
const history:StockHistory={registry:{id,symbol:'SYN',name:'Synthetic',type:'UNKNOWN',currency:'UNKNOWN'},registryAsOf:'2026-10-03',through:'2026-09-30',cutoff:'2026-10-01T12:00:00Z',limit:60,order:'MARKET_DATE_ASCENDING',rows:[]};
const result=():StockResult=>({history:structuredClone(history),screener:null,screenerError:'',portfolio:null,portfolioError:''});
test('Stocks navigation enabled and stable ID link is a real anchor',()=>{assert.doesNotMatch(renderToStaticMarkup(<Navigation page="stocks" onNavigate={()=>{}}/>),/Stocks · reserved/);assert.match(renderToStaticMarkup(<StockLink id={id}>SYN</StockLink>),new RegExp('href="/stocks/'+id+'"'));});
test('missing price, current metadata and outside scope remain honest',()=>{const html=renderToStaticMarkup(<StockResults result={result()} portfolioSelected={false}/>);for(const text of ['Current registry metadata','not fully knowledge-dated','Currency UNKNOWN','No visible canonical price','Insufficient usable history','Not evaluated by current Screener universe','No portfolio selected','UNAVAILABLE'])assert.ok(html.includes(text),text);assert.doesNotMatch(html,/NONE|0\.00/);});
test('available zero, WARMUP and DATA_BLOCKED preserve backend semantics',()=>{const r=result();r.screener={marketContext:{instrumentId:'other'},universeSnapshotId:'known',rows:[{instrumentId:id,eligibility:'DATA_BLOCKED',eligibilityReasons:['REFERENCE_MISSING'],setup:'NONE',setupEvaluated:false,setupReasons:[],trend:'UNKNOWN',ema20:0,ema50:null,fieldStates:{ema50:{availability:'WARMUP',reason:'INSUFFICIENT_HISTORY'}},provenance:{referenceSnapshotIds:[],priceBasis:'UNKNOWN'}}]} as unknown as ScreenerResponse;const html=renderToStaticMarkup(<StockResults result={r} portfolioSelected={true}/>);for(const text of ['DATA_BLOCKED','Not evaluated','WARMUP','INSUFFICIENT_HISTORY','0.00','AVAILABLE','Not held in selected portfolio'])assert.ok(html.includes(text),text);assert.doesNotMatch(html,/NONE \/ No setup/);});
test('fewer than two usable observations never creates a chart; isolated observations remain visible',()=>{for(const rows of [[],[{date:'2026-09-30',close:1}]])assert.doesNotMatch(renderToStaticMarkup(<PriceChart rows={rows}/>),/<svg/);const html=renderToStaticMarkup(<PriceChart rows={[{date:'2026-09-28',close:1},{date:'2026-09-29',close:null},{date:'2026-09-30',close:2}]}/>);assert.equal((html.match(/<circle/g)??[]).length,2);});
function harness(){const calls:{path:string;signal?:AbortSignal;resolve:(v:unknown)=>void;reject:(e:unknown)=>void}[]=[];let state:StockState=emptyStockState;const request:Request=<T,>(path:string,body?:unknown,signal?:AbortSignal)=>{assert.equal(body,undefined);return new Promise<T>((resolve,reject)=>calls.push({path,signal,resolve:v=>resolve(v as T),reject}));};return {calls,session:new StockSession(s=>{state=s;},request),state:()=>state};}
test('resolved history cutoff pins Screener and portfolio reads',async()=>{const h=harness(),pending=h.session.load(id,{through:history.through,cutoff:'',portfolioId:'selected'});assert.equal(new URL(h.calls[0].path,'http://test').searchParams.has('cutoff'),false);h.calls[0].resolve(history);await Promise.resolve();assert.equal(h.calls.length,3);for(const c of h.calls.slice(1)){const q=new URL(c.path,'http://test').searchParams;assert.equal(q.get('cutoff'),history.cutoff);assert.equal(q.get('through'),history.through);}h.calls[1].resolve({rows:[]});h.calls[2].resolve({holdings:[]});await pending;assert.equal(h.state().result?.history.cutoff,history.cutoff);});
test('draft edit aborts and late history cannot publish or start downstream reads',async()=>{const h=harness(),p=h.session.load(id,{through:history.through,cutoff:''});h.session.invalidate();assert.equal(h.calls[0].signal?.aborted,true);h.calls[0].resolve(history);await p;assert.deepEqual(h.state(),emptyStockState);assert.equal(h.calls.length,1);});
test('late downstream completion cannot overwrite a newer context',async()=>{const h=harness(),p=h.session.load(id,{through:history.through,cutoff:''});h.calls[0].resolve(history);await Promise.resolve();const newer=h.session.load(id,{through:'2026-09-29',cutoff:''});h.calls[2].resolve({...history,through:'2026-09-29'});await Promise.resolve();h.calls[3].resolve({rows:[]});await newer;h.calls[1].resolve({rows:[]});await p;assert.equal(h.state().result?.history.through,'2026-09-29');});
test('invalid UUID does not request and unknown UUID reports not found',async()=>{const h=harness();await h.session.load('bad',{through:history.through,cutoff:''});assert.equal(h.calls.length,0);assert.match(h.state().error,/Invalid/);const p=h.session.load(id,{through:history.through,cutoff:''});h.calls[0].reject(new ApiError('not found',404));await p;assert.match(h.state().error,/Instrument not found/);});
test('Screener service failure leaves retained history available',async()=>{const h=harness(),p=h.session.load(id,{through:history.through,cutoff:''});h.calls[0].resolve(history);await Promise.resolve();h.calls[1].reject(new ApiError('Unavailable',503));await p;assert.equal(h.state().result?.history,history);assert.equal(h.state().result?.screener,null);assert.equal(h.state().error,'');});

test('benchmark reference provenance is visible without inventing a stock setup',()=>{const r=result();r.screener={universeSnapshotId:'known',rows:[],marketContext:{instrumentId:id,trend:'UNKNOWN',volatility:'UNKNOWN',fieldStates:{},provenance:{referenceSnapshotIds:['index-reference'],priceBasis:'RAW_AS_TRADED'}}} as unknown as ScreenerResponse;const html=renderToStaticMarkup(<StockResults result={r} portfolioSelected={false}/>);assert.match(html,/Retained knowledge-dated evidence/);assert.match(html,/index-reference/);assert.doesNotMatch(html,/NONE \/ No setup/);});
