import { useEffect, useState } from 'react';
import { api, errorMessage } from './api';
import { cutoffIso, recorded, type Holding, type Thesis } from './view';
import { Badge, Dialog, Empty, Icon, InstrumentCell, LoadingSkeleton, Notice, PageHeader } from './ui';
export function ThesisJournal({portfolioId,holdings,cutoff,revision,onSaved}: {portfolioId:string;holdings:Holding[];cutoff:string;revision:number;onSaved:()=>Promise<void>}) {
 const [selected,setSelected]=useState(holdings[0]?.position.instrumentId??''),[rows,setRows]=useState<Thesis[]>([]),[offset,setOffset]=useState(0),[busy,setBusy]=useState(false),[error,setError]=useState('');const [dialog,setDialog]=useState<'new'|'invalidate'|null>(null);const [saving,setSaving]=useState(false),[saveError,setSaveError]=useState('');
 useEffect(()=>{if(!holdings.some(h=>h.position.instrumentId===selected)){setSelected(holdings[0]?.position.instrumentId??'');setOffset(0);}},[holdings,selected]);
 useEffect(()=>{if(!selected)return;const c=new AbortController();setBusy(true);setError('');setRows([]);void api<Thesis[]>(`/portfolios/${portfolioId}/holdings/${selected}/theses?${new URLSearchParams({cutoff:cutoffIso(cutoff),offset:String(offset),limit:'100'})}`,undefined,c.signal).then(r=>{if(!c.signal.aborted)setRows(r);}).catch(e=>{if(!c.signal.aborted)setError(errorMessage(e));}).finally(()=>{if(!c.signal.aborted)setBusy(false);});return ()=>c.abort();},[portfolioId,selected,cutoff,offset,revision]);
 const current=offset===0?rows[0]:null;const holding=holdings.find(h=>h.position.instrumentId===selected);
 return <><PageHeader eyebrow="WRITE THE REASON. KEEP THE RECORD." title="Thesis & mandate" subtitle="An explicit mandate, with versions you can return to."><span className="readonly-label"><Icon name="journal"/>Versioned journal</span></PageHeader>{!holdings.length?<Empty title="No open holdings">A recorded instrument position is needed before adding a thesis.</Empty>:<div className="thesis-layout"><aside className="panel thesis-list"><div className="thesis-list-head">YOUR HOLDINGS · {holdings.length}</div>{holdings.map(h=><button className={`thesis-symbol ${selected===h.position.instrumentId?'active':''}`} key={h.position.instrumentId} aria-pressed={selected===h.position.instrumentId} onClick={()=>{setSelected(h.position.instrumentId);setOffset(0);}}><InstrumentCell symbol={h.market.displaySymbol}/>{h.activeThesis&&<Badge>v{h.activeThesis.version}</Badge>}</button>)}</aside><div>{busy?<LoadingSkeleton/>:error?<Notice kind="error">{error}</Notice>:<>
 <section className="panel thesis-current"><div className="thesis-current-top"><InstrumentCell symbol={holding?.market.displaySymbol??'Instrument'}/><Badge kind={current?.active?'match':'outline'} icon="journal">{current?current.active?'ACTIVE':'INACTIVE':'No thesis'}</Badge></div>{current?<><div className="thesis-meta"><Badge kind="info">{current.mandate.replace('_',' ')}</Badge><span>Version {current.version}</span><span>Recorded {recorded(current.knownAt)}</span></div><p className="thesis-copy-label">Investment thesis</p><p className="thesis-copy">{current.text}</p><p className="thesis-copy-label">Invalidation condition / note</p><p className="invalidation">{current.invalidationNote??'No condition recorded.'}</p></>:<p className="thesis-copy">{offset?'Viewing historical versions. Return to the newest page for current actions.':'No thesis recorded. Add an explicit owner-authored mandate and thesis.'}</p>}<div className="thesis-actions"><button className="button primary" disabled={offset>0} onClick={()=>{setSaveError('');setDialog('new');}}><Icon name="plus"/>Create New Version</button><button className="button ghost" disabled={!current?.active} onClick={()=>{setSaveError('');setDialog('invalidate');}}><Icon name="missing"/>Invalidate Thesis</button></div></section>
 <section className="thesis-history"><div className="section-heading"><h2>Version history</h2><span className="muted">Every version is retained</span></div><div className="timeline">{rows.map(t=><article className="timeline-entry" key={t.id}><div className="timeline-top"><strong>v{t.version}</strong><Badge>{t.mandate.replace('_',' ')}</Badge><Badge kind={t.active?'outline':'missing'}>{t.active?'Active when recorded':'Inactive'}</Badge><time className="timeline-date">{recorded(t.knownAt)}</time></div><p>{t===current?'Current version':'Historical immutable version'}</p><details><summary>Read recorded version</summary><p>{t.text}</p><p>Invalidation: {t.invalidationNote??'Not recorded'}</p><p className="history-id">ID {t.id}{t.supersedes&&` · supersedes ${t.supersedes}`}</p></details></article>)}</div><div className="record-actions"><button className="button ghost" disabled={offset===0} onClick={()=>setOffset(offset-100)}>Newer versions</button><button className="button" disabled={rows.length<100} onClick={()=>setOffset(offset+100)}>Older versions</button></div></section></>}
 </div></div>}
 {dialog&&<Dialog eyebrow="APPEND A VERSION" title={dialog==='invalidate'?'Invalidate thesis':'Create new thesis version'} subtitle="Earlier versions remain immutable." onClose={()=>{if(!saving)setDialog(null);}}><form id="thesis-form" onSubmit={e=>{e.preventDefault();const f=Object.fromEntries(new FormData(e.currentTarget));setSaving(true);setSaveError('');void (async()=>{try{await api(`/portfolios/${portfolioId}/holdings/${selected}/theses`,{mandate:dialog==='invalidate'?current!.mandate:f.mandate,text:dialog==='invalidate'?current!.text:f.text,invalidationNote:f.invalidation||null,active:dialog!=='invalidate'});setOffset(0);await onSaved();setDialog(null);}catch(e){setSaveError(errorMessage(e));}finally{setSaving(false);}})();}}><div className="dialog-body"><Notice>{dialog==='invalidate'?'This records an inactive new version and preserves the last thesis text and mandate. It does not change holdings.':'Saving creates a new active version. It never edits an earlier record.'}</Notice>{dialog==='new'&&<><label className="field"><span>Mandate</span><select name="mandate" className="control" defaultValue={current?.mandate??'LONG_SWING'}>{['FAST_SWING','LONG_SWING','INVEST'].map(m=><option key={m}>{m}</option>)}</select></label><label className="field"><span>Thesis</span><textarea name="text" required maxLength={8000} defaultValue={current?.text??''}/></label></>}<label className="field"><span>{dialog==='invalidate'?'Invalidation reason':'Invalidation condition / note'}</span><textarea name="invalidation" required={dialog==='invalidate'} maxLength={4000} defaultValue={dialog==='new'?current?.invalidationNote??'':''}/></label>{saveError&&<Notice kind="error">{saveError}</Notice>}</div><div className="dialog-footer modal-actions"><button type="button" className="button ghost" disabled={saving} onClick={()=>setDialog(null)}>Cancel</button><button className={`button ${dialog==='invalidate'?'danger':'primary'}`} disabled={saving}>{saving?'Saving…':dialog==='invalidate'?'Append inactive version':'Create New Version'}</button></div></form></Dialog>}
 </>;
}
