import { useEffect, useRef, useState } from 'react';
import { api, errorMessage } from './api';
import { cutoffIso, jakartaToday, money, quantity, recorded, type Instrument, type LedgerEvent } from './view';
import { Badge, Dialog, Empty, Icon, InstrumentCell, LoadingSkeleton, Notice, PageHeader } from './ui';
export function EventDialog({portfolioId,instruments,original,onClose,onSaved}: {portfolioId: string;instruments: Instrument[];original?: LedgerEvent;onClose:()=>void;onSaved:()=>Promise<void>}) {
 const eventId=useRef(crypto.randomUUID());const [type,setType]=useState(original?.type??'CASH_DEPOSIT'),[busy,setBusy]=useState(false),[error,setError]=useState('');const trade=type==='BUY'||type==='SELL';
 return <Dialog title={original?'Correct transaction':'Record transaction'} eyebrow={original?'APPEND A CORRECTION':'APPEND AN IMMUTABLE EVENT'} subtitle={original?`${original.type} · ${original.tradeDate}`:'IDR · SHARES or explicit LOTS'} onClose={()=>{if(!busy)onClose();}}><form id="event-form" onSubmit={e=>{e.preventDefault();const f=Object.fromEntries(new FormData(e.currentTarget));setBusy(true);setError('');void (async()=>{try{await api(`/portfolios/${portfolioId}/events`,{eventId:eventId.current,type,instrumentId:trade?original?.instrumentId??f.instrument:null,tradeDate:f.date,quantity:trade?f.quantity:'0',unit:trade?f.unit:'SHARES',price:trade?f.price:'0',fees:f.fees,cashAmount:trade?'0':f.cash,externalReference:f.reference||null,source:'USER',note:f.note||null,supersedes:original?.id??null});await onSaved();onClose();}catch(e){setError(errorMessage(e));}finally{setBusy(false);}})();}}><div className="dialog-body">
 {original&&<><Notice>The original stays in history. Saving appends a new event that supersedes it.</Notice><dl className="immutable"><div><dt>Original event ID · immutable</dt><dd>{original.id}</dd></div><div><dt>Original recorded time · immutable</dt><dd>{recorded(original.knownAt)}</dd></div><div><dt>Instrument identity · immutable</dt><dd>{original.instrumentId??'Cash event'}</dd></div><div><dt>Existing correction lineage</dt><dd>{original.supersedes?`Supersedes ${original.supersedes}`:'Original event'}</dd></div></dl></>}
 <div className="fields"><label className="field"><span>Trade date</span><input name="date" type="date" min="1900-01-01" max={jakartaToday()} required defaultValue={original?.tradeDate??jakartaToday()}/></label><label className="field"><span>Type</span><select className="control" name="type" value={type} onChange={e=>setType(e.target.value)}>{(original?(original.instrumentId?['BUY','SELL']:['CASH_DEPOSIT','CASH_WITHDRAWAL']):['CASH_DEPOSIT','BUY','SELL','CASH_WITHDRAWAL']).map(t=><option key={t}>{t}</option>)}</select></label>
 {trade&&<>{!original&&<label className="field"><span>Instrument</span><select name="instrument" className="control" required><option value="">Select equity</option>{instruments.filter(i=>i.type==='EQUITY').map(i=><option key={i.id} value={i.id}>{i.symbol}</option>)}</select></label>}<label className="field"><span>Quantity</span><input name="quantity" type="number" min="0.01" max="1000000000" step="any" required defaultValue={original?.quantity??''}/></label><label className="field"><span>Unit</span><select className="control" name="unit" defaultValue="SHARES"><option>SHARES</option><option>LOTS</option></select><small>1 LOT = 100 SHARES; canonical events use SHARES.</small></label><label className="field"><span>Price · IDR</span><input name="price" type="number" min="0.00000001" max="1000000000000" step="any" required defaultValue={original?.price??''}/></label></>}
 {!trade&&<label className="field"><span>Cash amount · IDR</span><input name="cash" type="number" min="0.00000001" max="1000000000000" step="any" required defaultValue={original?.cashAmount??''}/></label>}<label className="field"><span>Fees · IDR</span><input name="fees" type="number" min="0" max="1000000000000" step="any" defaultValue={original?.fees??0} required/></label><label className="field"><span>{original?'New external reference':'External reference (optional)'}</span><input name="reference" maxLength={200} required={!!original} defaultValue={original?'correction-'+eventId.current:''}/></label></div><label className="field"><span>{original?'Correction note':'Note'}</span><textarea name="note" maxLength={4000} defaultValue={original?.note??''}/></label>{error&&<div className="form-error"><Notice kind="error">{error}</Notice></div>}</div><div className="dialog-footer modal-actions"><button type="button" className="button ghost" disabled={busy} onClick={onClose}>Cancel</button><button className="button primary" disabled={busy}>{busy?'Saving…':original?'Append correction':'Append event'} <Icon name="arrow"/></button></div></form></Dialog>;
}
export function Transactions({portfolioId,cutoff,instruments,revision,onSaved}: {portfolioId:string;cutoff:string;instruments:Instrument[];revision:number;onSaved:()=>Promise<void>}) {
 const [rows,setRows]=useState<LedgerEvent[]>([]),[offset,setOffset]=useState(0),[busy,setBusy]=useState(true),[error,setError]=useState('');const [dialog,setDialog]=useState<LedgerEvent|'new'|null>(null);const [filter,setFilter]=useState('all');
 useEffect(()=>{setOffset(0);},[portfolioId,cutoff]);
 useEffect(()=>{const c=new AbortController();setBusy(true);setError('');void api<LedgerEvent[]>(`/portfolios/${portfolioId}/events?${new URLSearchParams({cutoff:cutoffIso(cutoff),offset:String(offset),limit:'100'})}`,undefined,c.signal).then(r=>{if(!c.signal.aborted)setRows(r);}).catch(e=>{if(!c.signal.aborted)setError(errorMessage(e));}).finally(()=>{if(!c.signal.aborted)setBusy(false);});return ()=>c.abort();},[portfolioId,cutoff,offset,revision]);
 const shown=rows.filter(e=>filter==='all'||(filter==='active'?!e.correctedBy:!!e.correctedBy));
 return <><PageHeader eyebrow="AN IMMUTABLE RECORD" title="Transactions" subtitle="Corrections append new events. Original entries and recording times stay in history."><button className="button primary" onClick={()=>setDialog('new')}><Icon name="plus"/>Record transaction</button></PageHeader>
 {busy?<LoadingSkeleton/>:error?<Notice kind="error">{error}</Notice>:!rows.length?<Empty title="No transactions recorded">Record a cash deposit or import generic CSV transactions to start.</Empty>:<div className="panel"><div className="table-toolbar"><div className="tabs">{['all','active','superseded'].map(f=><button className={`tab ${filter===f?'active':''}`} key={f} aria-pressed={filter===f} onClick={()=>setFilter(f)}>{f[0].toUpperCase()+f.slice(1)}</button>)}</div><span className="table-note">History filters by recording cutoff; all trade dates are shown.</span></div><div className="table-scroll" tabIndex={0} aria-label="Immutable transactions; scroll horizontally"><table className="transaction-table"><thead><tr>{['Trade date','Recorded · WIB','Instrument','Type','Shares','Price · IDR','Fees · IDR','Cash · IDR','Lineage / status','Action'].map((h,i)=><th key={h} className={i>=4&&i<=7?'num':''}>{h}</th>)}</tr></thead><tbody>{shown.map(e=><tr key={e.id} data-event-id={e.id} className={`${e.correctedBy?'superseded':''} ${e.supersedes?'correction-child':''}`}><td>{e.tradeDate}</td><td>{recorded(e.knownAt)}</td><td><InstrumentCell symbol={instruments.find(i=>i.id===e.instrumentId)?.symbol??(e.instrumentId?'Instrument':'Cash')}/></td><td>{e.type}</td><td className="num">{e.instrumentId?quantity(e.quantity):'—'}</td><td className="num">{e.instrumentId?money(e.price):'—'}</td><td className="num">{money(e.fees)}</td><td className="num">{e.instrumentId?'—':money(e.cashAmount)}</td><td><Badge kind={e.correctedBy?'outline':'match'} icon={e.correctedBy?'history':'check'}>{e.correctedBy?'SUPERSEDED':'ACTIVE'}</Badge><details><summary className="correction-link">{e.supersedes?'↳ Superseding event':'Event details'}</summary><p className="history-id">ID {e.id}</p>{e.supersedes&&<p className="history-id">Supersedes {e.supersedes}</p>}{e.correctedBy&&<p className="history-id">Corrected by {e.correctedBy}</p>}{e.externalReference&&<p className="history-id">Reference {e.externalReference}</p>}{e.note&&<p>{e.note}</p>}</details></td><td>{!e.correctedBy&&<button className="text-button table-action" aria-label={`Correct transaction ${e.id}`} onClick={()=>setDialog(e)}><Icon name="history"/>Correct</button>}</td></tr>)}</tbody></table></div><div className="table-bottom"><span>{shown.length} events shown · originals remain immutable</span><span>Page {offset/100+1}</span></div></div>}
 <div className="record-actions"><button className="button ghost" disabled={busy||offset===0} onClick={()=>setOffset(offset-100)}>Previous events</button><button className="button" disabled={busy||rows.length<100} onClick={()=>setOffset(offset+100)}>Next events</button></div>{dialog&&<EventDialog portfolioId={portfolioId} instruments={instruments} original={dialog==='new'?undefined:dialog} onClose={()=>setDialog(null)} onSaved={async()=>{setOffset(0);await onSaved();}}/>}</>;
}
